### ISSUE TITLE
MeSH ID doesn't resolve correctly

### ISSUE THREAD

**Issue by bgyori** [identifiers-org/identifiers-org.github.io#101]
Consider the MeSH ID: D000073893 (https://meshb.nlm.nih.gov/record/ui?ui=D000073893).
For https://identifiers.org/mesh:D000073893, I get 
```
INVALID resolution request for 'mesh:D000073893', due to 'Resolution request 'mesh:D000073893' is NOT ABOUT A NAMESPACE; For namespace 'mesh', provided local ID 'D000073893' DOES NOT MATCH local IDs definition pattern '^(C|D)\d{6}$''
```
It looks like the pattern is too restrictive for MeSH IDs like this which have more than 6 numbers after the initial letter.

**Comment by mbdebian** [comment]
Thanks for reporting this @bgyori , we'll have a look at it as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Thanks again for reporting this, I have now fixed the regular expression in the registry.
Kind Regards,
Manuel
