### ISSUE TITLE
Errors in SwissLipids namespace

### ISSUE THREAD

**Issue by Midnighter** [identifiers-org/identifiers-org.github.io#102]
The SwissLipids (https://registry.identifiers.org/registry/swisslipid) sample URL does not resolve.

If one changes the sample URL to https://identifiers.org/swisslipid/SLM:000048885 it does work.

**Comment by mbdebian** [comment]
Hi @Midnighter , 
Thanks for reporting this issue, I just wanted to let you know that the record has been fixed in identifiers.org registry.
Kind Regards,
Manuel
