### ISSUE TITLE
Identifiers link for the GenBank record with accession  JAAVNF000000000.1

### ISSUE THREAD

**Issue by AlexandraPhil** [identifiers-org/identifiers-org.github.io#103]
Hi,

Can you please provide me with a working identifiers link for this GenBank data record: https://www.ncbi.nlm.nih.gov/nuccore/JAAVNF000000000.1? The accession ID is JAAVNF000000000.1 but the link https://identifiers.org/ncbi/insdc:JAAVNF000000000 which should have been resolving, isn't working.

Please see this example that resolves: https://identifiers.org/ncbi/insdc:MT253587.1.

Thanks a lot

Alexandra

**Comment by mbdebian** [comment]
Hi @AlexandraPhil ,
The problem with 'JAAVNF...' is that it doesn't match the regular expression that validates compact identifiers for 'insdc' namespace.
Please, have a look at this [test](https://regex101.com/r/JEGqj6/1) I've quickly tried online.
Also, please have a look at the error coming back from the resolution API.
```json
{
    "apiVersion": "1.0",
    "errorMessage": "INVALID resolution request for 'ncbi/insdc:JAAVNF000000000', due to 'Resolution request 'ncbi/insdc:JAAVNF000000000' is NOT ABOUT A NAMESPACE; For namespace 'insdc', provided local ID 'JAAVNF000000000' DOES NOT MATCH local IDs definition pattern '^([A-Z]\\d{5}|[A-Z]{2}\\d{6}|[A-Z]{4}\\d{8}|[A-J][A-Z]{2}\\d{5})(\\.\\d+)?$''",
    "payload": {
        "resolvedResources": [],
        "parsedCompactIdentifier": null
    }
}
```
With special attention to the error String
```
provided local ID 'JAAVNF000000000' DOES NOT MATCH local IDs definition pattern '^([A-Z]\\d{5}|[A-Z]{2}\\d{6}|[A-Z]{4}\\d{8}|[A-J][A-Z]{2}\\d{5})(\\.\\d+)?$'
```
Thanks again for reporting this, if you think this namespace needs an update on its ID space regular expression, please, don't hesitate to let me know, as we would need to get in touch with the relevant contact person for requesting up to date details on it.
Kind Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Hi @mbdebian, thanks for the swift response.

Is it possible to have a working link for this data record (even if this means getting in touch with the relevant people)? I understand that this may take some time, but it is important that we fix this, because we are most likely going to encounter this issue in the future again, with other data records.

Thanks a lot,

Alexandra

**Comment by mbdebian** [comment]
Thanks for getting back to me on this @AlexandraPhil .
Please, allow a few days for reaching out to the people responsible for this resources.
Kind Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Thank you very much for your help @mbdebian!

**Comment by mbdebian** [comment]
Dear @AlexandraPhil ,
I just wanted to let you know that we reached out to the relevant person on this issue, and we'll do our best to fix the issue as soon as the person gets back to us.
Kind Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Thanks a lot Manuel!

Cheers,
Alexandra

**Comment by mbdebian** [comment]
Just a quick update on this, @AlexandraPhil , to let you know that we're looking into this.
Thanks a lot for your understanding and your patience.
Kind Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Thank you very much for the update @mbdebian.

Best,
Alexandra

**Comment by mbdebian** [comment]
Hi @AlexandraPhil ,

Unfortunately, we haven't been able to liase with the resource on having this registry entry updated, I now have to close this issue as it's stalled in our support board.

Please, don't hesitate to let us know if we could be of help with anything else.

Kind regards,
Manuel

**Comment by AlexandraPhil** [comment]
Ok, thanks a lot for your efforts @mbdebian


Best,
Alexandra
