### ISSUE TITLE
How to make edit suggestion?

### ISSUE THREAD

**Issue by need47** [identifiers-org/identifiers-org.github.io#105]
The URL patterns for the following namespaces are deprecated:
https://registry.identifiers.org/registry/pubchem.compound
https://registry.identifiers.org/registry/pubchem.substance
https://registry.identifiers.org/registry/pubchem.bioassay

**Comment by mbdebian** [comment]
Thanks for reporting this back to us, @need47 
We'll have a look at it and try to resolve it.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Hi @need47 ,
I just wanted to offer an update on this, we've reviewed the aforementioned entries of the registry, and I just wanted to let you know that we are reaching out to the registered resources owners to address this request, which may take a while.
Kind Regards,
Manuel

**Comment by need47** [comment]
Thanks. Actually, we are the owner :)

**Comment by mbdebian** [comment]
OMG!
This is great then! hahaha!
Thanks a lot, could you then drop me an official e-mail with the details of the changes that you'd like to make in those entries?
Alternatively, you could also do it via a comment here.
Thanks again for your prompt reply!
Kind Regards,
Manuel

**Comment by need47** [comment]
We are the PubChem team. But we are not sure how/when the registries were created (probably by our institute). We'd like to make the following changes to the URL pattern.

For PubChem Compound:
from:
    https://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid={$id}
to:
    https://pubchem.ncbi.nlm.nih.gov/compound/{$id}

For PubChem Substance:
from: 
    https://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?sid={$id}
to:
    https://pubchem.ncbi.nlm.nih.gov/substance/{$id}

For PubChem BioAssay:
from:
    https://pubchem.ncbi.nlm.nih.gov/assay/assay.cgi?aid={$id}
to:
    https://pubchem.ncbi.nlm.nih.gov/bioassay/{$id}

**Comment by mbdebian** [comment]
Would you mind sending a confirmation email of these changes from a pubchem email address at NCBI to identifiers-org@ebi.ac.uk?
Thanks,
Manuel

**Comment by need47** [comment]
Sure. I'll cc our team leader as well.

**Comment by need47** [comment]
Thanks for your help. This has been resolved.
