### ISSUE TITLE
ARDB sample URL leads to a 404

### ISSUE THREAD

**Issue by eocarragain** [identifiers-org/identifiers-org.github.io#106]
Hi,
FYI, following the sample URL here https://registry.identifiers.org/registry/ardb results in a 404. The underlying ARDB database seems to no longer being maintained. 
Thanks,
Eoghan

**Comment by mbdebian** [comment]
Thanks a lot for pointing this out @eocarragain 
We'll get in touch with ARDB to find out what are the next steps for this namespace.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @eocarragain ,
I just wanted to let you know that we have reached out to CARD, on whether or not they would be interested on registering the platform in 'ardb' namespace, so ARDB data could still be accessible.
We'll move forward with a solution to this issue as soon as they get back to us.
Kind Regards,
Manuel

**Comment by eocarragain** [comment]
thanks @mbdebian

**Comment by mbdebian** [comment]
Dear @eocarragain ,

I just wanted to let you know that CARD expressed interest on taking over ARDB dataset resolutions via identifiers.org but, unfortunately, I don't have a timeline for this.

Please, don't hesitate to get back in touch in case you need anything else.

Kind regards,
Manuel
