### ISSUE TITLE
uniprot purls are not https

### ISSUE THREAD

**Issue by JervenBolleman** [identifiers-org/identifiers-org.github.io#108]
key | value
----- |---
Name | Universal Protein Resource using Persistent URL system  
URL Pattern | `http://purl.uniprot.org/uniprot/{$id} `

See the missing 's' after the http. While the other works for things like looking up webpages, it breaks RDF based tooling. 

Please revert this change.

**Comment by mbdebian** [comment]
Thanks for bringing this to our attention, we'll review this issue as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @JervenBolleman ,
I'm glad to let you know that we have just solved this issue. The update will be picked up by our resolution services shortly.
Thanks again for highlighting this issue.
Please, don't hesitate to let us know if you'd need anything else.
Kind Regards,
Manuel
