### ISSUE TITLE
hgnc.family example not working

### ISSUE THREAD

**Issue by wshayes** [identifiers-org/identifiers-org.github.io#109]
https://identifiers.org/hgnc.family:PADI

Is this record for hgnc.family still valid?

**Comment by mbdebian** [comment]
Thanks for bringing this to our attention, we'll review this issue as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Hi @wshayes ,
I just wanted to let you know that we have reached out to HGNC regarding this issue.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @wshayes ,
Sorry for the delay getting back to you on this.
After getting in touch with HGNC, I have been informed that 'hgnc.family' has been replaced by 'hgnc.genefamily'.
HGNC has asked identifiers.org to remove (deprecate) 'hgnc.family', and to encourage users to use 'hgnc.genegroup' instead.
I hope you find this information useful.
Please, don't hesitate to get back in touch in case you need anything else.
Kind Regards,
Manuel
