### ISSUE TITLE
MI (Molecular Interactions Ontology) does not resolve

### ISSUE THREAD

**Issue by pwrose** [identifiers-org/identifiers-org.github.io#110]
https://registry.identifiers.org/registry/psimi

Example url:
https://identifiers.org/MI:0308

Error:
INVALID resolution request for 'MI:0308', due to 'Resolution request 'MI:0308' is NOT ABOUT A NAMESPACE; UNKNOWN namespace 'mi' when verifying local ID '0308''

**Comment by mbdebian** [comment]
Thanks for bringing this to our attention, we'll review this issue as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @pwrose ,
I've been checking this one out, and it's actually a data inconsistency, 'psimi' should not be the prefix, it should be 'MI'.
This has now been fixed in the registry, and the updated information will be picked up by the resolution services in a few minutes.
Kind Regards,
Manuel
