### ISSUE TITLE
Addition of new identifier does not work

### ISSUE THREAD

**Issue by KarelBerka** [identifiers-org/identifiers-org.github.io#111]
I am trying to request identifiers for MolMeDB database with 
URL Pattern: https://molmedb.upol.cz/mol/{$id} 

where ${id} should have ^MM[0-9]{5}[0-9]*$ regex

so Sample ID MM00613 leads to  
https://molmedb.upol.cz/mol/MM00613 

but while this webpage links to acetic acid on our webpage, I got error message: 
Id 'MM00613' does not exist in 'https://molmedb.upol.cz/mol/MM00613'
that blocks me from finishing the request. 

What am I doing wrong?

**Comment by mbdebian** [comment]
Dear @KarelBerka ,
Thanks for raising this issue, we'll review it as soon as possible.
Please, keep in mind that COVID-19 and the number of Summer conferences identifiers.org is involved in, may stretch response times in our curation team.
Thanks in advance for your understanding.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Dear @KarelBerka ,
Sorry for the delay getting back to you.
Would you mind submitting all the details of your prefix registration request to us at our [email](mailto:identifiers-org@ebi.ac.uk) address?
This way we could find out whether this is a bug on our submission system or not.
Kind Regards,
Manuel
