### ISSUE TITLE
Case sensitivity issue in resolution of RRID:

### ISSUE THREAD

**Issue by awaisathar** [identifiers-org/identifiers-org.github.io#112]
[https://resolver.api.identifiers.org/RRID:AB_2532807](https://resolver.api.identifiers.org/RRID:AB_2532807) resolves correctly but [https://resolver.api.identifiers.org/rrid:AB_2532807](https://resolver.api.identifiers.org/rrid:AB_2532807) doesn't.

**Comment by mbdebian** [comment]
Hi @awaisathar ,
Thanks for reaching out on this, and sorry for the delay getting back to you.
Being the resolution services case insensitive, RRID happens to be a special prefix, where the LUIs (Locally Unique Identifiers) are allowed to be used straight away in the resolution API, thus, what it looks like a compact identifier, in fact, it's a LUI.
Please, have a look at this related [issue](https://github.com/identifiers-org/identifiers-org.github.io/issues/65) for a detailed explanation on this.
Kind Regards,
Manuel
