### ISSUE TITLE
ChEBI prefix

### ISSUE THREAD

**Issue by mihai-sysbio** [identifiers-org/identifiers-org.github.io#113]
I am a bit confused by the prefix used in the ChEBI identifier. When comparing the documentation pages for [MetaNetX chemical](https://registry.identifiers.org/registry/metanetx.chemical) and [ChEBI](https://registry.identifiers.org/registry/chebi) side by side, the difference is more obvious:

|   | ChEBI | MetaNetX chemical |
| - | ----- | -------|
| Local Unique Identifier (LUI) pattern | ^CHEBI:\d+$ | ^(MNXM\d+\|BIOMASS)$ |
| Prefix | CHEBI | metanetx.chemical |
| Sample URL | https://identifiers.org/CHEBI:36927 |  https://identifiers.org/metanetx.chemical:MNXM1723 |
| Sample Compact identifier | CHEBI:36927 | metanetx.chemical:MNXM1723 |
| Sample ID (LUI) | 36927 | MNXM1723 |

The `chebi:` prefix is not being used in the sample url.

I'm seeing explanations in #65 and #93 as to why `https://identifiers.org/CHEBI:36927` has been allowed, and I would not advocate for changing that. What I am puzzled by is why the more standard `https://identifiers.org/chebi:CHEBI:36927` is not allowed in addition to the above - most likely it was down to technical difficulties.

Would it be acceptable to remove the misleading `CHEBI` prefix from the documentation page?

**Comment by mbdebian** [comment]
Dear @mihai-sysbio ,

I'd like to thank you for reaching out on this matter, I really appreciate the time you've taken to explain the issue so nicely, as well as the investment in reading the explanations by the linked issues.

This is a controversial part of how the concepts of LUIs (Locally Unique Identifiers) and Compact Identifiers were a little bit bent over their backs to accommodate some particular requirements from the ontology communities.

Hopefully, the _Sample Compact Identifier_ field gives users useful information on how to create compact identifiers for a particular namespace.

I'm afraid removing the prefix information for those namespaces like CHEBI, VariO, GO... etc. may contribute to the confusion among the community, but, what we could probably do, is to implement a mechanism that highlights this special case, when applicable, in our landing pages.

I'll leave this issue open, to take it into account for the next iterations on the interface.

Thanks again for your feedback, @mihai-sysbio 

Kind Regards,
Manuel

**Comment by mihai-sysbio** [comment]
Thank you for the explanation @mbdebian .
May I suggest moving the row with the prefix lower down in the documentation, so that it is less observed? Or perhaps adding a separate section called `Usage` with only the `Sample Compact identifier` and the `Sample URL` would be useful. I'm not sure what _most_ people want to see in the documentation, but my intuition is that understanding how to convert an ID into a URL is would be a very popular need, and for that I gather those two fields are sufficient.

**Comment by mbdebian** [comment]
Hi @mihai-sysbio ,

I just wanted to let you know that we'll move these suggestions to our backlog, and I'll proceed on closing this ticket.

Thanks,
Manuel
