### ISSUE TITLE
ec-code issue with generic EC codes

### ISSUE THREAD

**Issue by tduigou** [identifiers-org/identifiers-org.github.io#115]
Hello,

Basically the issue is met by providing an "generic" EC number, eg "1.4.-.-". When providing the "https://identifiers.org/ec-code:1.4.-.-" it is resolved to "https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=1.4.-.-" but this lead to an error in IntEnz because the query expected is "[...]query?cmd=SearchEC&ec=1.4" (without the dashes), meanwhile when providing "https://identifiers.org/ec-code:1.4" it raises an error due to the Local Unique Identifier (LUI) pattern which enforce the presence of dashes for unknown digits.

Would it be possible to relax the LUI pattern to allow such "incomplete" / generic EC numbers, by allowing the 2nd, 3rd and 4th digits to be optional?

Best wishes,
Thomas

**Comment by mbdebian** [comment]
Hi @tduigou ,
Thanks a lot for reaching out, I just wanted to let you know that we'll have a look a this issue as soon as possible.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Hi @tduigou ,
I just wanted to let you know, as a quick update on this, that we're reaching out to the relevant providers in order to find out how we should proceed with the ID space definition update.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Hi @tduigou ,
I have reached out to INTENZ on this issue, and they let me know that INTENZ does not support incomplete EC Codes.
They have advised me to use Enzyme Portal for this case.
In this sense, it is possible to use a provider code in identifiers.org to force the resolution of a compact identifier to a specific provider in the namespace, in this case, to force the resolution of '1.4.-.-' to enzyme portal, 'enzymeportal' can be used in the resolution URL like this:
```
https://identifiers.org/enzymeportal/ec-code:1.4.-.-
```
I hope you find this information useful @tduigou , please, don't hesitate to get back in touch in case you need anything else.
Kind Regards,
Manuel

**Comment by bgyori** [comment]
I just wanted to comment on this, having run into the same issue as @tduigou. I actually found that currently, IntEnz does support incomplete EC codes, see e.g., https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=1.4 which resolves correctly. So I would suggest relaxing the LUI pattern to allow incomplete IDs.
