### ISSUE TITLE
SPARQL endpoint

### ISSUE THREAD

**Issue by yayamamo** [identifiers-org/identifiers-org.github.io#116]
I've not been able to issue a query for months to the following endpoint.
https://ebi.identifiers.org/services/sparql

Could you tell me the status or any new URL for the endpoint?

**Comment by mbdebian** [comment]
Dear @yayamamo ,
Thanks for reaching out on this issue.
ebi.identifiers.org was a domain redirection setup to point to the old EBI based identifiers.org platform, which end of life was announced back on June 2019 with the release of the new platform, to happen by the end of 2019.
Following that plan, the old platform was decommissioned back on beginning of January this year, and with it, its SPARQL endpoint.
The new identifiers.org platform holds registry data migrated from the old platform, and provides RESTful mechanisms for accessing it.
Could you please let me know what kind of information you're looking for? I may point you in the right direction for retrieving it from the new platform registry.
Kind Regards,
Manuel

**Comment by yayamamo** [comment]
Thanks. While I'll check the RESTful APIs, we maintain Umaka-YummyData ( https://yummydata.org/ ), and it checked the identifiers.org SPARQL endpoint. We'll stop it to check the URL.

**Comment by mbdebian** [comment]
Thanks @yayamamo ,
Please, don't hesitate to let me know if you need anything else.
Kind Regards,
Manuel
