### ISSUE TITLE
requirements for completeness for resources?

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#119]
I would like to request some guidance regarding the registration of resources and data completeness. For example, we are talking about the idea of registering Scholia (see https://riojournal.com/article/35820/) which has pages for DOI, PubMed ID, NCBI identifiers, ORCID, and a bunch more. However, we are not complete, that is, we do not have all DOIs, not all PubMed ID, not all ORCIDs.

Therefore, we were wondering (see https://github.com/fnielsen/scholia/issues/1184) if not being complete is a reason to not register as a Resource?

**Comment by mbdebian** [comment]
Hi @egonw ,
You're right, this is a question on ID space coverage and whether or not it's a requirement for registering a resource in Identifiers.org.
As we already have resources that don't fully cover the IDs in the namespace where they are registered, I see no problem with  registering the platform you mention, as a resource for each namespace where it is going to provide the local resolutions.
Please, don't let me know if you'd need anything else, also I can offer some help with the registration process if necessary.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
I’d like to reopen this issue for having an open conversation around this topic.

**Comment by egonw** [comment]
Does it benefit interoperability of life sciences databases if we can only link resources that have full coverage for an identifier? How does this relate to databases that are not up to date, but 1 or more release behind the main database, and therefore frequently behind?

**Comment by mbdebian** [comment]
Hi @egonw ,

I just wanted to let you know that, after an internal debate, I have approved the resource registration requests for Scholia, based on either the existence of a primary provider, or promotion of an existing one, in the namespace where Scholia was requested to be added as alternate provider.

Please, don't hesitate to let me know in case you need anything else.

Kind regards,
Manuel

**Comment by egonw** [comment]
Hi @mbdebian, I did notice and happy to hear this! Thanks.
