### ISSUE TITLE
correction for name of resource

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#120]
Currently, the resource [looks like this](https://registry.identifiers.org/registry/wikipathways#!):

![image](https://user-images.githubusercontent.com/26721/91935370-d8631d80-eced-11ea-87a6-94283b8d1bc2.png)

But I hope the name and description can be updated to `WikiPathways` with an upper case P.

**Comment by mbdebian** [comment]
Yes, no problem, I just updated the entry.
Thanks,
Manuel
