### ISSUE TITLE
how do I define resource priority?

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#121]
Thank you for adding Scholia as resource for the `wikipathways` namespace:

![image](https://user-images.githubusercontent.com/26721/92081153-efc00a80-edc2-11ea-928b-cbc4f935e367.png)

I just realize that I am not sure how to indicate that Scholia is a secondary provider, and that when I click the example `identifiers.org` example, I now get linked to Scholia and not the primary resource, WikiPathways itself.

Can you please provide guidance how I an indicate when I'm submitting Scholia for other namespaces that is is not the primary provider?

**Comment by mbdebian** [comment]
Hi @egonw ,
I have just flagged WikiPathways as the primary resource, it should be picked up by the resolution services in a few minutes.
When submitting Scholia as a provider for other namespaces, as they already exist in identifiers.org, Scholia would not be set as the primary provider, so there is no need for extra information. Although, the 'additional information' text box could be use for highlighting this to the curator.
Thanks,
Manuel
