### ISSUE TITLE
possibly wrong submit button text

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#122]
The form to propose a new resource has a button that says `Submit prefix request` as visible in this screenshot:

![image](https://user-images.githubusercontent.com/26721/92305738-43308500-ef8a-11ea-99d1-768b0e06f17d.png)

But I guess the text on this form should be `Submit resource request`?

**Comment by mbdebian** [comment]
Nice catch @egonw !
I'll have a look at it, as I need to refine a few things on the user interface.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
Hi @egonw ,
I just wanted to let you know that I have fixed this issue.
Thanks again for reporting it!
Kind regards,
Manuel
