### ISSUE TITLE
ena identifiers link not working

### ISSUE THREAD

**Issue by TrisSN** [identifiers-org/identifiers-org.github.io#123]
Hi,

This link goes to the ncbi page, and cannot find the project: https://identifiers.org/ena.embl:ERP119623

I can reach it via SRA (https://identifiers.org/insdc.sra:ERP119623 ), but the project was deposited in ENA, and identifiers.org search suggests the ENA version is fine.

I don't need notifying of a resolution to this, as I'll use the second link. However, I thought it worth telling you the behaviour of identifiers seems wrong and confusing here.

Tris

**Comment by mbdebian** [comment]
Hi @TrisSN ,

I'm glad to let you know that I have already fixed this issue.

Kind regards,
Manuel
