### ISSUE TITLE
Additional identifier pattern for GWAS Catalog

### ISSUE THREAD

**Issue by ljwh2** [identifiers-org/identifiers-org.github.io#124]
The GWAS Catalog has a new (additional) identifier pattern which is two digits longer than the existing one. We need to add this to identifiers.org, please can you advise if we need to fill in the request prefix form, or something else? At the moment, we do not have a landing page for these new identifiers but we are working on this.

**Comment by ljwh2** [comment]
Scrap that last comment - we do have landing pages for these identifiers. So we just need to register the new identifier pattern.

**Comment by mbdebian** [comment]
Hi Laura,
Sorry for the delay getting back to you.
For a new identifier pattern, we’re probably looking at a new namespace (prefix), you can use the prefix registration [form](https://registry.identifiers.org/prefixregistrationrequest) to provide the details.
Please, don’t hesitate to let me know in case you need anything in the process.
Thanks,
Manuel

**Comment by ljwh2** [comment]
Hi, Sorry, I wasn't clear - the prefix is the same, but the overall identifier is 2 digits longer in the new format. It looks like I can't use the prefix reg form since the prefix already exists. Is it possible to update the regex pattern for that prefix from ^GCST\d{6}$ to ^GCST\d{6}\d*$

**Comment by mbdebian** [comment]
Hi Laura,
Yes, it is possible to update the regular expression.
Would you like me to set up '^GCST\d{6}\d*$' as the new regular expression that describes the ID Space?
Which namespace are we talking about?
Kind regards,
Manuel

**Comment by mbdebian** [comment]
Ok, I have located the [namespace](https://registry.identifiers.org/registry/gcst) we are talking about.
Should I update the regular expression to '^GCST\d{6}\d*$'?
Kind regards,
Manuel

**Comment by ljwh2** [comment]
That's correct, yes please

**Comment by mbdebian** [comment]
Done!
Please, don't hesitate to let me know if you need anything else.
Kind regards,
Manuel
