### ISSUE TITLE
ENA identifiers link not directing to ENA repository

### ISSUE THREAD

**Issue by AlexandraPhil** [identifiers-org/identifiers-org.github.io#125]
Hi,

I would like to raise the following: The link https://identifiers.org/ena.embl:PRJEB39409 should direct to the European Nucleotide Archive (ENA) repository, but instead, the landing page is NCBI Nucleotide.

Could you please resolve this issue?

Thanks a lot,
Alexandra Philiastides

**Comment by mbdebian** [comment]
Hi @AlexandraPhil ,

After reviewing the namespace information, I wanted to let you know that I just updated the provider information at [ena.embl](https://registry.identifiers.org/registry/ena.embl) as a follow up on your reported issue.

I'd like to thank you as well for submitting valuable feedback to us at identifiers.org.

Please, don't hesitate to get back in touch in case you experience any other issues.

Kind regards,
Manuel

**Comment by AlexandraPhil** [comment]
This is great @mbdebian, thank you so much!

Alexandra
