### ISSUE TITLE
pgx prefix with new target

### ISSUE THREAD

**Issue by mbaudis** [identifiers-org/identifiers-org.github.io#126]
For Progenetix `pgx` We have settled to a general resolver scheme, where 

* Progenetix biosample: `pgx:pgxbs-kftva5zv`
  - <https://progenetix.org/services/ids/pgxbs-kftva5zv> or <https://progenetix.org/services/ids/pgx:pgxbs-kftva5zv> (i.e. prefix stacking will be resolved)

There will be some other ids (callsets, subjects, publications...), updated soon; but for now I'd like to see changed in identifiers org:

* Sample URL: `https://identifiers.org/pgx:pgxbs-kftva5zv`
* Sample Compact identifier: `pgx:pgxbs-kftva5zv`
* Sample ID (LUI): `pgxbs-kftva5zv`
* Local Pattern: `^\w{5,6}-[\w[\w\.\-]{4,127}$`
* Resolver: `https://progenetix.org/services/ids/___id___`

**Comment by mbdebian** [comment]
Dear @mbaudis ,

I’d like to thank you for your request and to let you know that we’ll review it shortly.

Kind regards,
Manuel

**Comment by mbaudis** [comment]
@mbdebian Thanks! Pls. let me know if this is a good way to ask for changes / what would be better. The online form cannot be used for only submitting changes, AFAIK,

**Comment by mbdebian** [comment]
Hi @mbaudis ,

This is perfectly ok for submitting update requests, as you mention, the resource registration request form is for new resources.

Kind regards,
Manuel

**Comment by mbdebian** [comment]
Hi @mbaudis ,

I'm reviewing the regular expression you provided
```
^\w{5,6}-[\w[\w\.\-]{4,127}$
```

And it looks like it may have an extra '**[**' that may cause problems for the parser.

I have tried a corrected version
```
^\w{5,6}-[\w\w\.\-]{4,127}$
```

Which also validates the IDs you mention.

Is that correct?

Thanks,
Manuel

**Comment by mbaudis** [comment]
Ooops ... I have a keyboard with over-sensitive "v" key, resulting sometimes in double pastings :-/

Fixed, and cleaned up a bit. Thanks!

```
^\w{5,7}-[\w.-]{4,128}$
```

**Comment by mbdebian** [comment]
Thanks for the update @mbaudis 

I have just made the changes to [pgx](https://registry.identifiers.org/registry/pgx) namespace to reflect your requested changes.

Kind regards,
Manuel

**Comment by mbaudis** [comment]
> Thanks for the update @mbaudis
> 
> I have just made the changes to [pgx](https://registry.identifiers.org/registry/pgx) namespace to reflect your requested changes.
> 
> Kind regards,
> Manuel

+1 !
