### ISSUE TITLE
Wikidata properties are not well resolved by the regular wikidata prefix

### ISSUE THREAD

**Issue by RichardBruskiewich** [identifiers-org/identifiers-org.github.io#128]
You folks have https://registry.identifiers.org/registry/wikidata

However (bless their souls), the Wikimedia folks have a distinct base URI for their Wikidata "Property" entries, which has `Property:` in the path. For example: https://www.wikidata.org/wiki/Property:P2293

In some practical circumstances, we set `WIKIDATA_PROPERTY` prefix to `https://www.wikidata.org/wiki/Property:` thus allowing a CURIE something like `WIKIDATA_PROPERTY:P2293`.

Please kindly advise what would be preferred.

**Comment by mbdebian** [comment]
Dear @RichardBruskiewich ,
I just wanted to thank you for submitting this issue, and to let you know that we are looking into it.
Kind regards,
Manuel

**Comment by RichardBruskiewich** [comment]
Thanks @mbdebian !

**Comment by mbdebian** [comment]
Hi @RichardBruskiewich ,

I'd like to apologize for the delay looking into this, and to thank you in advance for your patience and understanding.

The identifiers.org registry entry for [wikidata](https://registry.identifiers.org/registry/wikidata) seems to be devoted to Wikidata Items, in this case, I would advise to have another namespace, e.g. 'wikidata.property', registered with all the information needed to access Wikidata Properties.

I'll raise this question for internal discussion, and reach out to wikidata if needed.

Thanks again for your patience and understanding.

Kind regards,
Manuel

**Comment by andrawaag** [comment]
Changing the URL pattern in identifiers.org from https://www.wikidata.org/wiki/{$id} to http://www.wikidata.org/entity{$id} (note the missing s in http!) should allow resolving both Qids (Items) and Pids (Properties) to wikidata.

**Comment by mbdebian** [comment]
Thanks a lot for your help on this @andrawaag !

I've just made the changes to the [Wikidata](https://registry.identifiers.org/registry/wikidata) namespace.

Kind regards,
Manuel
