### ISSUE TITLE
Runtime Memory Limit Review

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/identifiers-org.github.io#13]
Apparently, JVM memory use is difficult to tame, so this topic will need a proper review and, probably, the creation of a startup.sh entry point for the containers, that calculates de proper parameters for correctly tuning JVM memory usage.

**Comment by JervenBolleman** [comment]
In java 11 you can use -

-XX:InitialRAMPercentage
-XX:MaxRAMPercentage=75
-XX:MinRAMPercentage=25

etc.

Java 12 onwards G1GC will more aggressively free memory back to the OS.

**Comment by mbdebian** [comment]
Thanks for the hint @JervenBolleman !!!
I'll have a look at those parameters
Thanks again,
Manuel
