### ISSUE TITLE
Cannot find a way to edit an existing collection

### ISSUE THREAD

**Issue by ivanmicetic** [identifiers-org/identifiers-org.github.io#130]
For editing collections, [documentation pages](https://docs.identifiers.org/articles/docs/faq.html#how-do-you-modify-an-existing-collection) indicate that there should be a ‘Suggest modifications to this data collection’ link but none can be found on a registry page. How to update an existing record?

**Comment by mbdebian** [comment]
Hi @ivanmicetic ,

Thanks for reporting this, we'll review the documentation pages soon.

Kind regards,
Manuel

**Comment by ivanmicetic** [comment]
Thanks. But still, what is the current procedure for updating records? I tried to update [DisProt](https://registry.identifiers.org/registry/disprot) entry when applying for new [disprot.region](https://registry.identifiers.org/registry/disprot.region) but my comments to the maintainers ended up in the description of disprot.region. disprot entry still shows old data...

**Comment by mbdebian** [comment]
Hi @ivanmicetic ,

There is no specific form for updating records, you can let us know via GitHub issues, which is our preferred feedback / communication mechanism.

Thanks,
Manuel
