### ISSUE TITLE
Unreliable confirmation link eMail

### ISSUE THREAD

**Issue by sneumann** [identifiers-org/identifiers-org.github.io#131]
Hi, I'd like to claim and edit a record, and created a profile (it is username sneumann :-) 
I did not get an eMail confirmation, nothing in the spam folder, and no success even after
I whitelisted the identifiers.org domain. I did create a second test profile (sneumann2) 
associated with my gmail, which did come through. Our email is managed by the microsoft 
cloud exchange services, so I could imagine they reject the mail even before it reaches 
my whitelist. 
I see several options 1) please activate my account sneumann and/or 2) let us engage in a few 
test emails to debug why the mails didn't come through, I guess I won't be the only victim 
or 3) tell me to use the test account sneumann2 and forget about the proper solution. 
Yours, Steffen

**Comment by mbdebian** [comment]
Hi @sneumann ,

Thanks for reporting this issue, we'll have a look at what may be going on with the confirmation emails.

Kind regards,
Manuel

**Comment by mbdebian** [comment]
Hi @sneumann ,

I just wanted to let you know that we have reviewed our email gateway configuration, and it's working with no issues.

Not being sure what could have happened when you tried to register in identifiers.org, I'd like to point out that our users are not required to register on the platform to perform any action beyond the features that are available to the community without authentication.

At identifiers.org we only require our curators to have an account on the platform, in order for them to make changes in the registry.

I'd like to thank you for reporting this issue, and for your patience and understanding while we checked our systems.

Please, don't hesitate to let us know in case you need anything else.

Kind regards,
Manuel
