### ISSUE TITLE
Change URL Pattern for MassBank

### ISSUE THREAD

**Issue by sneumann** [identifiers-org/identifiers-org.github.io#132]
Hi, 
on https://registry.identifiers.org/registry/massbank we (me and @tsufz) would like to update the URL pattern.

Currently it is 
http://www.massbank.eu/MassBank/jsp/FwdRecord.jsp?id={$id}
e.g. http://www.massbank.eu/MassBank/jsp/FwdRecord.jsp?id=PB000166
which has 1) a hostname issue, correct is massbank.eu without www, and 
2) the jsp/FwdRecord.jsp does not exist anymore. 

Correct is:
https://massbank.eu/MassBank/RecordDisplay?id={$id}
and
http://www.massbank.jp/RecordDisplay?id={$id}

Similarly, we need to fix the Home URL (just for EU) 
from www.massbank.eu to massbank.eu

Thanks in advance, 
Yours, Steffen

**Comment by mbdebian** [comment]
Hi @sneumann ,

Thanks for your request, we are working on it.

Kind regards,
Manuel

**Comment by mbdebian** [comment]
Hi @sneumann ,

I just wanted to let you know that these corrections have been applied to identifiers.org registry.

Kind regards,
Manuel

**Comment by sneumann** [comment]
Awesome, I can confirm looks good now. Thanks, Steffen
