### ISSUE TITLE
Issue during prefix registration

### ISSUE THREAD

**Issue by marcadella** [identifiers-org/identifiers-org.github.io#133]
There is an issue with the registration of a new prefix. I get the following error on the `Sample Id` field:
`Id 'SFB_COVID19_MW286762' does not exist in 'https://covid19.sfb.uit.no/api/records/SFB_COVID19_MW286762'`

What I have:
- `Sample Id`: `SFB_COVID19_MW286762`
- `regex pattern`: `^\w+_COVID19_\w+$`
- `URL Pattern`: `https://covid19.sfb.uit.no/api/records/{$id}`

**Comment by marcadella** [comment]
I tried with the API and I got the same issue:
`{"apiVersion":"1.0","errorMessage":"INVALID Prefix registration request due to 'Id 'SFB_COVID19_MW286762' does not exist in 'https://covid19.sfb.uit.no/api/records/SFB_COVID19_MW286762''","payload":{"comment":"No comments on your prefix registration request","token":""}}`

The payload was:
```
{
	"apiVersion": "1.0",
	"payload": {
		"name": "SARS-CoV-2",
		"description": "Curated contextual database gathering samples related to SARS-CoV-2 virus and covid-19 disease.",
		"requestedPrefix": "covid19",
		"sampleId": "SFB_COVID19_MW286762",
		"idRegexPattern": "^\\w+_COVID19_\\w+$",
		"references": [],
		"additionalInformation": "",
		"institutionName": "University of Tromsø - The Arctic University of Norway",
		"institutionHomeUrl": "https://uit.no/startsida",
		"institutionDescription": "Organization information obtained from ROR API using ROR ID 'https://ror.org/00wge5k78' with Wikidata IDs [Q279724], and ISNI IDs [0000000122595234]",
		"institutionLocation": "NO",
		"providerName": "Elixir@UiT",
		"providerCode": "sfb",
		"providerDescription": "Elixir@UiT is the local branch of ELIXIR-NO node based at UiT.",
		"providerHomeUrl": "https://covid19.sfb.uit.no",
		"providerUrlPattern": "https://covid19.sfb.uit.no/api/records/{$id}",
		"providerLocation": "NO",
		"requester": {
			"name": "Mayeul Marcadella",
			"email": "mma227@uit.no"
		}
	}
}
```

**Comment by marcadella** [comment]
Turns out the issue was that the URL `https://covid19.sfb.uit.no/api/records/SFB_COVID19_MW286762` was not valid.
No issue then, but it would be nice if the error message was something like `URL xyz not reachable`.

**Comment by mbdebian** [comment]
Thanks for your feedback @marcadella , we take note of it.

Kind regards,
Manuel
