### ISSUE TITLE
Update the VMH website url

### ISSUE THREAD

**Issue by rmtfleming** [identifiers-org/identifiers-org.github.io#135]
Please replace http://vmh.uni.lu/ with https://www.vmh.life/

Also, please update these:
Location | Luxembourg -> Location | Galway, Ireland

Institution | Luxembourg Centre for Systems Biomedicine, University of Luxembourg -> Institution | National University of Ireland, Galway

Thank you.
@ithiele

**Comment by hHermjakob** [comment]
Done, please let me know if not ok.
Best regards,
Henning
