### ISSUE TITLE
VMH links

### ISSUE THREAD

**Issue by ithiele** [identifiers-org/identifiers-org.github.io#136]
Hello

could you please update the links to vmh entries? It should be https://www.vmh.life/ not vmh.uni.lu.

For metabolites, the link is: https://www.vmh.life/#metabolite/
For reactions, the link is: https://www.vmh.life/#reaction/
For genes, the link is: https://www.vmh.life/#gene/

Thank you very much.

Ines

**Comment by hHermjakob** [comment]
Dear Ines, 
thanks for the notification, done. Could you please check?
Best regards,
Henning
