### ISSUE TITLE
chembl identifiers link not working

### ISSUE THREAD

**Issue by TrisSN** [identifiers-org/identifiers-org.github.io#138]
identifiers gave this link for a chembl dataset: https://identifiers.org/chembl.target:CHEMBL4303805
it doesn't resolve. However, using the base ID CHEMBL4303805 in the chembl site, the data can be reached.

**Comment by hHermjakob** [comment]
Where did the link came from ? The direct reason for the error is that CHEMBL4303805 is not a ChEMBL Target, but an Assay. We'll look into adding a namespace for Assays or a generic search interface, but we can't resolve this on the identifiers.org side directly.

**Comment by TrisSN** [comment]
Hi. This accession ID was provided by the authors of a manuscript we will be publishing. 
When typing 'chembl' into the identifiers.org search, two options come up: 'target' and 'compound'. In this case, 'compound' didn't work at all, so I assumed it was 'target'. 
I've used the standard URL (not identifiers) in this case. Thanks for looking into it, and I hope it's resolved for the next CHEMBL dataset that comes to us.

**Comment by hHermjakob** [comment]
Hi,
it took a while, but we now have a proper solution. ChEMBL has implemented a general link for all its identifiers, and this is available as, for example, https://identifiers.org/chembl:CHEMBL4303805 . We will retain the original chembl.compound and chembl.target namespaces in identifiers.org, but the recommended one for all classes now is simply 'chembl'. In fact your original link https://identifiers.org/chembl.target:CHEMBL4303805 , while not recommended, now also works, as ChEMBL now does a more error-tolerant mapping. So, for the next dataset, you should be able to just use
https://identifiers.org/chembl:CHEMBLxxxx
Best regards,
Henning
