### ISSUE TITLE
Incorrect pattern for `pid.pathway`

### ISSUE THREAD

**Issue by cthoyt** [identifiers-org/identifiers-org.github.io#139]
Prefix: `pid.pathway`
Actual: `^\w+$`
Expected: `^\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b$`

This corresponds to a UUID. Currently, `\w` does not handle the dashes.

**Comment by hHermjakob** [comment]
The bigger problem right now seems to be that http://pid.nci.nih.gov/ does not respond. I don't find any mention of the db since about 2010. Do you have information on whether it's still operational, or a new URL?

**Comment by cthoyt** [comment]
This database is dead as far as I can tell. The pathways have been copied to NDEx at https://www.ndexbio.org/#/user/301a91c6-a37b-11e4-bda0-000c29202374 but there's very little information available about if this is official or whether there will be any maintenance.

**Comment by cthoyt** [comment]
See also: https://wiki.nci.nih.gov/pages/viewpage.action?pageId=315491760

**Comment by hHermjakob** [comment]
The id.org entry does not aim to model the UUID, but the first column of 
https://github.com/NCIP/pathway-interaction-database/blob/master/download/NCI-Pathway-Info.xlsx
The UUID would be more correct, but we don't want to change the pattern now for a dead resource, that's likely to cause more damage than good (if anything at all).

**Comment by cthoyt** [comment]
Oh, I see. Then I agree it's best to leave it
