### ISSUE TITLE
Contribution instructions

### ISSUE THREAD

**Issue by cthoyt** [identifiers-org/identifiers-org.github.io#143]
I've just left several issues (#142 #141, #140, #139) that all have obvious fixes. Is there a single source of truth against which I could send a pull request to update the data backing identifiers.org? If so, it would be great to post contribution instructions such that I could send a small PR for each issue.

**Comment by hHermjakob** [comment]
No, as of now it's individual issues. However, email me if you want to do large scale validation/update etc.
