### ISSUE TITLE
Pattern resolution issue for fplx

### ISSUE THREAD

**Issue by bgyori** [identifiers-org/identifiers-org.github.io#144]
The URL pattern for `fplx` (see https://registry.identifiers.org/registry/fplx) is defined as
```
http://bioportal.bioontology.org/ontologies/FPLX/?
p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFPLX_{$id}
```
it appears that `https://identifiers.org/fplx:RAS` resolves to 
```
https://bioportal.bioontology.org/ontologies/FPLX/?
p=classes&conceptid=http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFPLX_RAS
```
with the `%` signs from the pattern having been replaced with `%25`, i.e., escaped twice. Can the pattern itself or the pattern resolution logic be changed to fix this?

**Comment by mbdebian** [comment]
Dear @bgyori ,
I'd like to thank you for reporting this.
I have now updated the URL pattern to not encode the redirecting URL, as it seems to not be decoded on the bioportal side before the concept lookup happens, which ends up in an error page.
Although I haven't been able to run a final test, as it looks like Bioportal has become unavailable (see attached screen capture)
Kind regards,
Manuel
<img width="1904" alt="Captura de pantalla 2021-03-14 a las 12 39 43" src="https://user-images.githubusercontent.com/8855107/111068903-8a13b000-84c2-11eb-8b7d-25ffd736c54f.png">
