### ISSUE TITLE
URL resolution of UBERON terms

### ISSUE THREAD

**Issue by arnikz** [identifiers-org/identifiers-org.github.io#145]
Hi,

I've tried the following:
https://identifiers.org/UBERON:0001062 -> http://purl.obolibrary.org/obo/UBERON_0001062 (OK)
https://identifiers.org/UBERON/0001062 -> _INVALID resolution request..._

however, this is not an issue with e.g., NCIT or NCBITaxon:

http://identifiers.org/ncit:C37927 or http://identifiers.org/ncit/C37927 -> http://purl.obolibrary.org/obo/NCIT_C37927 (OK)
or
https://identifiers.org/taxonomy:9397 or https://identifiers.org/taxonomy/9397 -> http://purl.obolibrary.org/obo/NCBITaxon_9397 (OK)

Would it be possible to enable/use both  `:` and `/` in the URLs consistently?
Thank you.

**Comment by hHermjakob** [comment]
Dear Arnikz,
my apologies for the delayed response, I had to investigate a bit. Unfortunately we can't enable this style of resolution for UBERON, basically for historical reasons. UBERON and other "GO-style" resources have historically considered the prefix (UBERON) part of the identifier, rejecting the second option. Of course we could enable resolution on our side, but we normally follow the requests of the data resources.
Best regards,
Henninig
