### ISSUE TITLE
how to make updates to identifiers.org

### ISSUE THREAD

**Issue by zhilianghu** [identifiers-org/identifiers-org.github.io#146]
We found you have our Animal QTLdb in 4 separate entries, cattle, chicken, pig, and sheep, (e.g. https://registry.identifiers.org/registry/cattleqtldb ; https://registry.identifiers.org/registry/pigqtldb ; etc.) while actually this is a single database.  We have a standard xref for accessing our data registered at http://amigo.geneontology.org/xrefs#Animal_QTLdb -- and the way you listed may subject to change although they work now, how can we get it updated?

**Comment by hHermjakob** [comment]
Dear Zhiliang,
I have now updated the entries for cattle, pig, chicken, sheep as requested, and introduced a new species independent namespace "qtldb". Please check and let me know if you require any further changes.
Best regards,
Henning

**Comment by zhilianghu** [comment]
Dear Henning,
Thank you for your great works!
Zhiliang
