### ISSUE TITLE
Updates to DisProt and DisProt region namespaces

### ISSUE THREAD

**Issue by ivanmicetic** [identifiers-org/identifiers-org.github.io#147]
DisProt resource was operated by Indiana University in the US until 2016 when it was rewritten and expanded by a consortium lead by University of Padua, Italy (as DisProt version 7). Today we are at the second major revision of DisProt database ([DisProt 8](https://doi.org/10.1093/nar/gkz975)). With this request, we would like to gain ownership of DisProt entry in identifiers.org substituting Indiana University with [University of Padua](https://ror.org/00240q980).
Other changes for [DisProt](https://registry.identifiers.org/registry/disprot) namespace are:
- Description: DisProt is a database of intrinsically disordered proteins and protein disordered regions, manually curated from literature.
- Resource name: DisProt
- Resource description: DisProt
- URL Pattern: https://disprot.org/{$id}
- Home URL: https://disprot.org/
- Location: Italy
- Institution: University of Padua
- Institution ROR ID: https://ror.org/00240q980

Changes for [DisProt region](https://registry.identifiers.org/registry/disprot.region) namespace are:
- Description: DisProt is a database of intrinsically disordered proteins and protein disordered regions, manually curated from literature.
- Resource description: DisProt region
- URL Pattern: https://disprot.org/{$id}
- Home URL: https://disprot.org/
- Institution ROR ID: https://ror.org/00240q980

Thanks,
Ivan

**Comment by hHermjakob** [comment]
Done.
