### ISSUE TITLE
Update of the metanetx.* prefixes

### ISSUE THREAD

**Issue by smoretti** [identifiers-org/identifiers-org.github.io#149]
Hi

could you update the following entries?
I requested them but don't know how to update them by myself now.

- metanetx.chemical
The pattern is now: `^(MNXM\d+|BIOMASS|WATER)$`

- metanetx.reaction
The pattern is now: `^(MNXR\d+|EMPTY)$`
URL Pattern is now: `https://www.metanetx.org/equa_info/{$id}`

- metanetx.compartment
The pattern is now: `^(MNX[CD]\d+|BOUNDARY|IN|OUT)$`
URL Pattern is now: `https://www.metanetx.org/comp_info/{$id}`

For all of them:
Home URL is now `https://www.metanetx.org/`
Institution ROR ID is `https://ror.org/002n09z45`

Thanks

**Comment by hHermjakob** [comment]
Done. Please let me know if there are problems.

**Comment by smoretti** [comment]
Thanks this is perfect.

Only the Institution ROR ID is missing but maybe setting it will erase the other institution fields
