### ISSUE TITLE
Issue with MGE provider

### ISSUE THREAD

**Issue by cthoyt** [identifiers-org/identifiers-org.github.io#153]
The [mge](https://registry.identifiers.org/registry/mge#) provider has the wrong format URL. 

Actual: `http://aclame.ulb.ac.be/perl/Aclame/Genomes/mge_view.cgi?view=info&id=mge:{$id}`
Expected: `http://aclame.ulb.ac.be/perl/Aclame/Genomes/mge_view.cgi?view=info&id={$id}`

Example: http://aclame.ulb.ac.be/perl/Aclame/Genomes/mge_view.cgi?view=info&id=00000063

**Comment by renatocjn** [comment]
I'm getting connection timeouts. Perhaps it went offline?

**Comment by cthoyt** [comment]
Same here, it seems to have been dead for a long time. The Bioregistry has an automated weekly [health check](https://biopragmatics.github.io/bioregistry/health/) for all prefixes that we can look into to see if it's dead or maybe just an issue today. Here's what it's been saying for the last few months, it seems to be consistently down:

| date       | working   |
|------------|-----------|
| 2023-01-01 | False     |
| 2022-12-25 | False     |
| 2022-12-18 | False     |
| 2022-12-11 | False     |
| 2022-12-04 | False     |
| 2022-11-27 | False     |
| 2022-11-20 | False     |
| 2022-11-13 | False     |
| 2022-11-06 | False     |
| 2022-10-30 | False     |
| 2022-10-23 | False     |
| 2022-10-16 | False     |
| 2022-10-09 | False     |
| 2022-10-02 | False     |
| 2022-09-28 | False     |
| 2022-09-28 | False     |
| 2022-09-28 | False     |
| 2022-09-28 | False     |

Code:

```python
import yaml
import requests
from tabulate import tabulate

res = requests.get("https://raw.githubusercontent.com/biopragmatics/bioregistry/main/docs/_data/health.yaml")
data = yaml.safe_load(res.text)
rv = []
for run in data["runs"]:
    for result in run["results"]:
        if result["prefix"] == "mge":
            rv.append((run["date"], result.get("status_code") == 200))

print(tabulate(rv, headers=["date", "working"], tablefmt="github"))
```

**Comment by renatocjn** [comment]
I'm going to deactivate this namespace. I can't find anything online about a relocation nor can I contact the people involved. Thank you @cthoyt for bring this up.
