### ISSUE TITLE
Wrong Regexp for ENVO ontology

### ISSUE THREAD

**Issue by marcadella** [identifiers-org/identifiers-org.github.io#156]
There is an issue with the regex registered for the [ENVO ontology](https://registry.identifiers.org/registry/envo): the following id uses `\d{7}` instead of `\d{8}`: [ENVO:2000004](https://www.ebi.ac.uk/ols/ontologies/envo/terms?obo_id=ENVO:2000004).
Note that it is distinct from [ENVO:02000004](https://www.ebi.ac.uk/ols/ontologies/envo/terms?obo_id=ENVO:02000004).

**Comment by hHermjakob** [comment]
Done, thanks!
