### ISSUE TITLE
MetaCyc database: Local Unique Identifier (LUI) pattern too restrictive

### ISSUE THREAD

**Issue by tduigou** [identifiers-org/identifiers-org.github.io#157]
Hello,

For instance the compound ID `PROTON` is a valid ID (direct link: https://metacyc.org/compound?orgid=META&id=PROTON) but it does not match the current LUI pattern (which is `^CPD-\d{5}$`). I suggest the pattern should be open up to any valid alphanumeric string (including `-` and `_`).

Best wishes,

**Comment by tduigou** [comment]
It appears this issue has been already pointed out here #69. It is probably worth asking again to MetaCyc.
Best wishes,

**Comment by hHermjakob** [comment]
As Manuel has already tried several times to reach MetaCyc,  I have now taken the examples given here and in issue #69, plus their website, as enough evidence to relax the pattern. Thanks!
