### ISSUE TITLE
please update the MIR:00100301 record

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#158]
The current record is:

```
Name | CAS through Common Chemistry
Description | CAS through Common Chemistry
URL Pattern | http://commonchemistry.org/ChemicalDetail.aspx?ref={$id}
Home URL | http://commonchemistry.org
Location | United States
Sample ID (LUI) | 50-00-0
Institution | CAS American Chemical Society
Institution ROR ID
```

Please update to:

```
Name | CAS Common Chemistry
Description | CAS Common Chemistry
URL Pattern | https://commonchemistry.cas.org/detail?cas_rn={$id}
Home URL | http://commonchemistry.cas.org/
Location | United States
Sample ID (LUI) | 50-00-0
Institution | CAS American Chemical Society
Institution ROR ID
```

While at it, the name of the identifier is "CAS Registry Number" (syn: CAS RN).

**Comment by hHermjakob** [comment]
Thanks for pointing out, done with slight change to URL pattern, used the one given in the CAS "Cite..." section.

**Comment by egonw** [comment]
thanks!

**Comment by zmughal** [comment]
It appears that the current `urlPattern` does not point at the correct location for CAS RNs. I have added a PR on the registry using the data from this issue.

**Comment by renatocjn** [comment]
Dear @zmughal,

Thank you for going so far as to create a PR for this. Unfortunately, the repository you worked on is deprecated, the current repository for the registry web service is at https://github.com/identifiers-org/cloud-hq-ws-registry and the registry data is recorded in our relational database. You can access the current registry entry for CAS at https://registry.identifiers.org/registry/cas.

Comparing your PR and the current entry, the urlPatterns are different:
- on your PR: https://commonchemistry.cas.org/detail?cas_rn=${lid}
- on the registry: https://commonchemistry.cas.org/detail?ref={$id}

I see that both patterns work([registry](https://commonchemistry.cas.org/detail?ref=50-00-0) and [PR](https://commonchemistry.cas.org/detail?cas_rn=50-00-0)), do you have any information on which should be used?

**Comment by egonw** [comment]
The URL pattern from the pull request is preferred. See the publication: https://pubs.acs.org/doi/full/10.1021/acs.jcim.2c00268

**Comment by renatocjn** [comment]
URL pattern updated. Thank you @egonw and @zmughal.
