### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by arjundahalard** [identifiers-org/identifiers-org.github.io#159]
I found Namespace amazing, as per RFCs publications, and even about computing, as a space between any two alphabets does plays important role. But I lack proper computing knowledge, and thus got confused, about topics of regex or such topics. Thus though to inquire if by means of email, details can be submitted or not, to make global registry, with uniqueness in name and identification.

**Comment by hHermjakob** [comment]
Dear Arjundahalard,
identifiers.org is a registry of data resources, with a focus on bioinformatics. Please refer to our publications https://docs.identifiers.org/articles/docs/publications.html for further information.
Best regards,
Henning
