### ISSUE TITLE
Issue with ena.embl identifier

### ISSUE THREAD

**Issue by marcadella** [identifiers-org/identifiers-org.github.io#163]
Clicking on the [sample URL](https://identifiers.org/ena.embl:BN000065) redirects to https://www.ebi.ac.uk/ena//ena/browser/view/BN000065, which is a broken link. The reason is that the link should points to https://www.ebi.ac.uk/ena/browser/view/BN000065 instead.

**Comment by marcadella** [comment]
I dug dipper and had a look at the redirection chain:

```
> wget https://identifiers.org/ena.embl:BN000065 2>&1
--2021-07-23 09:26:43--  https://identifiers.org/ena.embl:BN000065
Resolving identifiers.org (identifiers.org)... 35.186.253.75
Connecting to identifiers.org (identifiers.org)|35.186.253.75|:443... connected.
HTTP request sent, awaiting response... 302 
Location: https://www.ebi.ac.uk/ena/data/view/BN000065 [following]
--2021-07-23 09:26:43--  https://www.ebi.ac.uk/ena/data/view/BN000065
Resolving www.ebi.ac.uk (www.ebi.ac.uk)... 193.62.193.80
Connecting to www.ebi.ac.uk (www.ebi.ac.uk)|193.62.193.80|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.ebi.ac.uk/ena//ena/browser/view/BN000065 [following]
--2021-07-23 09:26:44--  https://www.ebi.ac.uk/ena//ena/browser/view/BN000065
Reusing existing connection to www.ebi.ac.uk:443.
HTTP request sent, awaiting response... 404 Not Found
2021-07-23 09:26:44 ERROR 404: Not Found.
```

It looks like identifiers.org is properly redirecting to the set up URL (https://www.ebi.ac.uk/ena/data/view/BN000065) and then it is EBI who is wrongly redirecting.

So all that needs to be done is to update both `ena.embl` and `bioproject` to use the up to date URLs (i.e. replace `data` by `browser`).

**Comment by hHermjakob** [comment]
Resolved.
