### ISSUE TITLE
Colon in prefix `mmmp:biomaps` causes issues parsing CURIEs

### ISSUE THREAD

**Issue by cthoyt** [identifiers-org/identifiers-org.github.io#165]
The algorithm to parse a CURIE is typically to string split on the leftmost colon (or specified delimiter) and therefore prefixes should not contain any of the characters that are typically used as delimiters (e.g., colon `:`, right slash `/`, underscore `_`).

An alternative algorithm is to dynamically compile a regular expression for what a CURIE "is" that enumerates all of the prefixes w.r.t. a given registry, but this just doesn't feel right.

I'd request that this prefix is renamed to `mmmp.biomaps` as the dot `.` character has been used as a safe delimiter in several other instances (e.g., `pubchem.compound`).

**Comment by hHermjakob** [comment]
Although it's a change in namespace, which normally should be avoided, I don't see an alternative here, as it's clearly not functional as is. TBD.

**Comment by cthoyt** [comment]
Any updates?

**Comment by renatocjn** [comment]
I will be closing this since the biomaps is not available anymore anyway.

**Comment by cthoyt** [comment]
As https://registry.identifiers.org/registry/mmmp:biomaps has not been removed from the Identifiers.org service, I don't think that it's appropriate to close this issue without addressing it

**Comment by renatocjn** [comment]
I mean the repository http://www.mmmp.org/MMMP/public/biomap/listBiomap.mmmp where resolutions were directed to. In the future, the namespace will be turned into a tombstone record as the data is not available anymore. The specifics of the implementation of tombstones in idorg are still under discussion.
