### ISSUE TITLE
Forwarding for FMA and OPB terms leads to BioPortal message "The page you are looking for wasn't found"

### ISSUE THREAD

**Issue by maxneal** [identifiers-org/identifiers-org.github.io#168]
When I enter either of the following URIs into a browser, I am directed to a page on BioPortal that says "The page you are looking for wasn't found. Please try again."

https://identifiers.org/FMA:280791
http://identifiers.org/fma/FMA:280791

I've tried this with several other FMA terms and the result is the same. Similar behavior for OPB terms. For example 
https://identifiers.org/OPB:OPB_00340.

Is there an issue with the way identifiers.org forwards FMA and OPB URIs to BioPortal?

**Comment by renatocjn** [comment]
Maybe there is a mistake on the FMA ID used. The sample id in [our FMA entry](https://identifiers.org/FMA:67112) resolves fine. I also can't find the ID 280791 in the fma ontology via bioportal or EBI's OLS. I will be closing this since it is quite old.
