### ISSUE TITLE
Prefix NCBI:txid is recommended by NCBI, but not accepted by identifiers.org

### ISSUE THREAD

**Issue by chrishmorris** [identifiers-org/identifiers-org.github.io#171]
Thank you for identifiers.org, which is helping us support interoperability for our customers.

For the NCBI taxonomy, identifiers.org uses "taxonomy:" as the prefix, but the NCBI recommend "NCBI:txid". See for example: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9606.

It would be better if the two authorities were in agreement. Perhaps the simplest fix is for the identifiers.org resolver to accept NCBI:txid as an alternative.

**Comment by renatocjn** [comment]
We actually have several providers under that namespace to account for several taxonomies. This allows for search in them by using the same prefix. I will be closing this issue since it is quite old.

**Comment by cthoyt** [comment]
@chrishmorris I would highly suggest petitioning NCBI to change their suggestion, the `NCBI:txid` conflates what it means to be a compact URI (CURIE) and uses `NCBI` as the prefix and therefore something like `txid9606` as the local unique identifier. This is bad in two ways: 1) NCBI is ambiguious, used in different communities to refer to different namespaces. For example, taxonomy people assume NCBI means NCBITaxon. Model Organism Databases assume it means NCBI Gene. 2) txid is redundant of the namespace itself in the local unique identifier itself, which isn't great. 

There is a related issue that `taxonomy` is a very generic prefix that doesn't match `NCBITaxon` used in most other registries, and might be difficult to disambiguate in some resources that use ITIS, GBIF, etc., but that's not the main issue here

**Comment by chrishmorris** [comment]
Thank you, I have made a suggestion to the NCBI.

**Comment by chrishmorris** [comment]
Further to this, [BioPortal](https://bioportal.bioontology.org/ontologies/NCBITAXON) uses the prefix "NCBITAXON:" and https://github.com/obophenotype/ncbitaxon uses "NBCITaxon".

Conrad Schoch at the NLM pointed out: "While the NCBI taxonomy is the most authoritative resource, it is not the only one."  

Can I persuade you to add "ncbi.taxon:" as an alternative to "taxonomy"? That might open the way to some convergence, that will help make our data more FAIR. If you are able to allow two alternative prefixes, that will be a non-breaking change.

**Comment by renatocjn** [comment]
Hi @chrishmorris,

Generally, we try not to have redundant namespaces in our registry. This only causes more confusion in the future when trying to make systems more interoperable. One of the goals of the identifiers.org registry strikes to achieve is to be a source of truth for people referencing data via compact identifiers. 

You are welcome to make a namespace request on our website to have the `ncbitaxon` prefix registered, but unless given a good enough reason, I don't think it will be accepted. Are these the same data objects? Would there be any difference in referencing taxonomy:9606 and ncbitaxon:9606? 

An actual solution to this would be for the community to choose which to use and the other to be deprecated in both systems. But I doubt this will be done anytime soon.

I don't think this is important to the matter here but I though it would be good to mention that one can reference explicitly the ncbitaxon pages in bioportals and OLS using the current `taxonomy` namespace. You just have to use provider codes:
- http://identifiers.org/ols/taxonomy:9606
- http://identifiers.org/bptl/taxonomy:9606
