### ISSUE TITLE
UBERON mapping is broken

### ISSUE THREAD

**Issue by satra** [identifiers-org/identifiers-org.github.io#172]
https://identifiers.org/UBERON:0002435 - no longer resolves.

**Comment by cthoyt** [comment]
We solved this in the Bioregistry by rewiring resolution to go through OLS and not BioPortal. More context at https://github.com/biopragmatics/bioregistry/pull/249

**Comment by renatocjn** [comment]
@satra The change was made to use OLS instead of bioportal. Sorry for the delay to solve this.
