### ISSUE TITLE
ATCC identifier prefix

### ISSUE THREAD

**Issue by JosuaCarl** [identifiers-org/identifiers-org.github.io#173]
ATCC prefix identifier might be deprecated. https://identifiers.org/atcc:_identifier_ only leads to homepage of ATCC, not to specified organism. https://www.atcc.org/products/_identifier_ should be the target. 11303 and 29328 were tried as identifiers.

**Comment by renatocjn** [comment]
I have changed the pattern to the new one. Thank you for catching the problem.
