### ISSUE TITLE
Cell lines ontology

### ISSUE THREAD

**Issue by chrishmorris** [identifiers-org/identifiers-org.github.io#177]
Can you please create Curies for https://www.ebi.ac.uk/ols/ontologies/clo ?

**Comment by cthoyt** [comment]
@chrishmorris in the mean time the Bioregistry has you covered https://bioregistry.io/registry/clo

**Comment by chrishmorris** [comment]
I tried and I am stuck on "Please, try again later. The form contents will be saved until you navigate away from identifiers.org."

It feels a little odd - I hope that the University of Michigan is happy with the proposal.

**Comment by renatocjn** [comment]
It is odd that you don't have any other error messages when submitting the form. Could you copy the information here? Or just printscreen the filled form.

**Comment by chrishmorris** [comment]
I have the same error message. Here is a copy of the page just before submitting (with Chrome).

[Identifiers.org.pdf](https://github.com/identifiers-org/identifiers-org.github.io/files/10447070/Identifiers.org.pdf)

**Comment by chrishmorris** [comment]
Thank you.

**Comment by renatocjn** [comment]
CLO is online now.
see https://registry.identifiers.org/registry/clo#!

Thank you Chris.

**Comment by chrishmorris** [comment]
Thank you!
