### ISSUE TITLE
resolver is down

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#178]
For example for https://identifiers.org/pubchem.compound/2818 :

![image](https://user-images.githubusercontent.com/26721/144986236-4a7ace84-2ca9-4172-8397-a7ceb582f804.png)

**Comment by egonw** [comment]
btw, https://identifiers.org/pubchem.compound:2818 doesn't work either (the compact id variant)

**Comment by renatocjn** [comment]
It is working now
