### ISSUE TITLE
Please change GlycoNAVI information.

### ISSUE THREAD

**Issue by yamadaissaku** [identifiers-org/identifiers-org.github.io#180]
# Namespace: GlycoNAVI

* Please change the following information.

## General Information

LUI: `^GN_[A-Za-z0-9_:]+$`

## Identification schemes

Sample URL | https://identifiers.org/glyconavi:GN_GlyTouCan_G03681DA
-- | --
Sample Compact identifier | glyconavi:GN_GlyTouCan_G03681DA
Sample ID (LUI) | GN_GlyTouCan_G03681DA

## Resources

Sample ID (LUI) | GN_GlyTouCan_G03681DA
-- | --

**Comment by yamadaissaku** [comment]
https://identifiers.org/glyconavi:GN_GlyTouCan_G03681DA

```
INVALID resolution request for 'glyconavi:GN_GlyTouCan_G03681DA', due to 'Resolution request 'glyconavi:GN_GlyTouCan_G03681DA' is NOT ABOUT A NAMESPACE; For namespace 'glyconavi', provided local ID 'GN_GlyTouCan_G03681DA' DOES NOT MATCH local IDs definition pattern '^GN_[A-Za-z0-9]+$''
```

**Comment by cthoyt** [comment]
@yamadaissaku if the identifiers.org team is unresponsive you can feel free to propose the same update in the Bioregistry (https://bioregistry.io, https://github.com/biopragmatics/bioregistry). 

It's a drop-in replacement that integrates Identifiers.org and several other registries, but has an open data / open curation model so it's easier to make improvements. The page for GlycoNAVI is displayed here: https://bioregistry.io/glyconavi. It looks like the same issue exists now if you try and resolve your example with https://bioregistry.io/glyconavi:GN_GlyTouCan_G03681DA, so we can make this update for you immediately.

**Comment by renatocjn** [comment]
@yamadaissaku The resolution seems to work at the moment, do you still need the local ID and LUI pattern updated?

Please direct update requests to identifiers-org@ebi.ac.uk for it to be handled by our curation team. We are trying to keep the GitHub issues for development discussions.

Best regards.

**Comment by renatocjn** [comment]
I will be closing this since thing seem fine now.
