### ISSUE TITLE
Cannot modify records I created

### ISSUE THREAD

**Issue by marcadella** [identifiers-org/identifiers-org.github.io#181]
After loging in and clicking on `Curation`, I am taken back to the home page, so I cannot modify my own records.

**Comment by cthoyt** [comment]
@marcadella while you're waiting for the Identifiers.org to provide support, you can feel free to directly edit records for resources you own (or anything that you're knowledgeable about!) in the Bioregistry (https://bioregistry.io) on its open source database in GitHub at https://github.com/biopragmatics/bioregistry
