### ISSUE TITLE
Fungal Barcode (fbol) identifiers are not resolved

### ISSUE THREAD

**Issue by piotr-gawron** [identifiers-org/identifiers-org.github.io#183]
Even Sample URL for fbol identifier: https://identifiers.org/fbol:2224 is not resolved properly. I get 400 Bad request.

I think this is similar to the issue with CABRI (#162). However, in this case the reason might be that the URL pattern contains a space.

**Comment by cthoyt** [comment]
Bioregistry seems to be able to handle this https://bioregistry.io/fbol:2224 on a technical level, but the URI format seems to point to a dead resource. Can you give an example URL that provides for `fbol:2224`? While we wait for the Identifiers.org team, we can issue a fix in the Bioregistry directly.

**Comment by renatocjn** [comment]
Fungal barcode seems to be offline. 404 responses from several resolvers (idorg, bioregistry and n2t). The original issue seems to be due to our verification of the return code before redirection. That can be seen from the invalid URL message.

**Comment by cthoyt** [comment]
@renatocjn would you consider improving the invalid URL message page? it's very hard to understand in most cases and its lack of styling makes it a bit too technical looking

**Comment by renatocjn** [comment]
Definitely, it is already in the development queue :)
