### ISSUE TITLE
invalid prefix and sample id for Gramene Growth Stage Ontology

### ISSUE THREAD

**Issue by piotr-gawron** [identifiers-org/identifiers-org.github.io#184]
I think the prefix contains invalid character "\" that breaks resolving the identifiers. Moreover sample id should be `GRO:0007133` without extra "\".

**Comment by cthoyt** [comment]
See also similar issues:

- https://github.com/identifiers-org/identifiers-org.github.io/issues/99
- https://github.com/identifiers-org/identifiers-org.github.io/issues/155

**Comment by cthoyt** [comment]
Note we solved these issues in the Bioregistry. Sorry for all the similar responses, but we were also sort of frustrated with the current state and are happy that the Bioregistry provides an alternative that can be more easily updated.

You should be able to resolve CURIEs like this with: https://bioregistry.io/gramene.growthstage:0007133 - we could also add `GRO` as a prefix synonym if you think it would also be valuable to be able to resolve CURIEs looking like  https://bioregistry.io/GRO:0007133 - let me know :)

**Comment by renatocjn** [comment]
Resolution is working again. Unfortunately, I had to change the prefix to GRO due to how the resolver is implemented. If this breaks something for anyone, please let me know. Here is [the new URL](https://registry.identifiers.org/registry/gro#!) for the namespace.
