### ISSUE TITLE
problem with resolution of mmmp:biomaps (Melanoma Molecular Map Project Biomaps) identifiers

### ISSUE THREAD

**Issue by piotr-gawron** [identifiers-org/identifiers-org.github.io#185]
Sample ID https://identifiers.org/mmmp:biomaps:37 is not resolved properly (I get 400 Bad Request).

I suspect that the reason is that prefix contains ":" which is used by tokenizer.

**Comment by cthoyt** [comment]
Hi @piotr-gawron, you could also check in on #165. We actually fixed this in the Bioregistry so you can use it as a drop in replacement like https://bioregistry.io/mmmp:biomaps:37 -- however, it looks like the MMMP site has been taken down, so even with the technical fix for resolving the malformed CURIE, this is still not super helpful. If you happen to know if there's a new website, we can update it in the Bioregistry while we wait for the Identifiers.org team to respond
