### ISSUE TITLE
Can't create entry for OMIM

### ISSUE THREAD

**Issue by luciansmith** [identifiers-org/identifiers-org.github.io#189]
I tried to create an request for OMIM at

https://registry.identifiers.org/prefixregistrationrequest

but it refused to recognize that the id

139150

was valid for

https://www.omim.org/entry/{$id}

despite the fact that it is.

I suspect that 'omim' used to be part of identifiers.org, given that biomodels #4 has a reference to it (http://identifiers.org/omim/139150)

**Comment by jonrkarr** [comment]
In my experience, the form is a little buggy. The id input haa to be changed after the regex pattern and URL pattern are entered to re-trigger the validation.

**Comment by luciansmith** [comment]
Yeah, I did indeed re-enter the id input a few times, but no luck.

**Comment by jonrkarr** [comment]
I couldn't get the form to work for OMIM either

Here's the submission:
- Namespace name:  Online Mendelian Inheritance in Man
- Description: OMIM is a comprehensive, authoritative compendium of human genes and genetic phenotypes that is freely available and updated daily. 
- Requested Prefix: omim
- Sample Id: 139150
- Regex pattern: ^\d+$
- Supporting references
  - https://doi.org/10.1093/nar/gky1151
  - https://doi.org/10.1093/nar/gku1205
  - https://doi.org/10.1093/nar/gkn665
  - https://doi.org/10.1093/nar/gki033
- ROR id: https://ror.org/00za53h95
- Provider code: jhu
- URL Pattern: https://www.omim.org/entry/{$id}

Environment
- Windows 10
- Chrome 97.0.4692.71

**Comment by cthoyt** [comment]
There's already an entry for OMIM at https://registry.identifiers.org/registry/mim. Not sure where the "o" went.

**Comment by cthoyt** [comment]
FYI the Bioregistry uses the more standard `omim` as the canonical prefix for OMIM, but also handles prefix synonyms for backwards compatibility and has external mappings to the prefixes used in Identifiers.org, Prefix Commons, N2T, etc..

The page for OMIM is at https://bioregistry.io/omim and you can use the Bioregistry as a drop-in replacement for the identifiers.org resolver while we wait for them to respond with URLs like https://bioregistry.io/omim:603903

**Comment by renatocjn** [comment]
Thanks for catching the existing entry @cthoyt. @luciansmith and @jonrkarr, please use the existing entry.
If you want, I can check the reason that the form was blocking the submission if you inform me the error message that you where given.

Best regards.
