### ISSUE TITLE
Add entry for PSI-MI

### ISSUE THREAD

**Issue by luciansmith** [identifiers-org/identifiers-org.github.io#190]
https://www.psidev.info/mif

Biomodels 399, 788, 843, 896, and 965 all use 'psimi' as an identifiers.org namespace, but it doesn't seem to exist (any more?)  Not sure how to request it be added, other than adding this ticket.

**Comment by luciansmith** [comment]
Here's all the references:

`````
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000399/BIOMD0000000399_url.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0501"/>
BIOMD0000000788/Schropp2019.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0914"/>
BIOMD0000000788/Schropp2019.xml:                    <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0914"/>
BIOMD0000000788/Schropp2019.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0914"/>
BIOMD0000000788/Schropp2019.xml:                    <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0914"/>
BIOMD0000000843/Dudziuk2019.xml:        <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0908"/>
BIOMD0000000896/Szymanska2009.xml:      <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0908"/>
BIOMD0000000965/LeBeau1999_Phosphorylation_CCK.xml:     <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0217"/>
BIOMD0000000965/LeBeau1999_Phosphorylation_CCK.xml:     <rdf:li rdf:resource="http://identifiers.org/psimi/MI:0203"/>

``````

**Comment by cthoyt** [comment]
@luciansmith seems like these are just nonsense URIs for the molecular interactions vocabulary that include a redundant prefix - in the identifiers.org style, you could switch to https://identifiers.org/MI:0501

While you're waiting for a response from the Identifiers.org team, you could also check out the Bioregistry's entry on http://bioregistry.io/registry/mi and construct URIs like https://bioregistry.io/mi:0501 or using any of the URIs listed on https://bioregistry.io/reference/mi:0501

**Comment by luciansmith** [comment]
Oh, hey, good catch!  Looks like I can just replace 'psimi' with 'mi' and it'll work:

http://identifiers.org/mi/MI:0914

And thanks for the bioregistry link!  I'll definitely keep an eye on that, especially if identifiers.org turns out to not be able to do updates any more.

**Comment by cthoyt** [comment]
This situation is a bit more complicated, it looks like Identifiers.org does still make sporadic updates, but the major issue is that the responsible people are not engaging with community discussion on this tracker and are pretty selective about which emails they respond to/follow-up on. I'm under the impression that EBI has a lot of problems like this at the moment where projects are being scrapped, underfunded, don't have personnel who can address technical improvements, etc.

**Comment by renatocjn** [comment]
Seems like this was solved. Thanks for the help @cthoyt. For more information on idorg update situation check issue #169.
