### ISSUE TITLE
Please remove GeneDB from identifiers.org

### ISSUE THREAD

**Issue by uliboehme** [identifiers-org/identifiers-org.github.io#192]
Dear identifiers.org, 

GeneDB (https://www.genedb.org/) has been taken offline. 

Please remove https://registry.identifiers.org/registry/genedb#!. 

Thanks, 
Uli Boehme

**Comment by dhimmel** [comment]
I think there might be a way to note that a resource is deprecated rather than deleting it entirely.

**Comment by cthoyt** [comment]
Identifiers.org indeed has this, but while you wait for them to respond, we can update this in the Bioregistry (https://bioregistry.io, https://github.com/biopragmatics/bioregistry)

The PR is https://github.com/biopragmatics/bioregistry/pull/369 - @uliboehme if you send me your ORCID then I can properly attribute you for the contribution.

**Comment by renatocjn** [comment]
Hello, Thank you for notifying us of this.
We will be keeping the namespace online as a way for existing links still inform users that it was taken offline.
