### ISSUE TITLE
Old ebi.identifiers.org/search links in Web services documentation

### ISSUE THREAD

**Issue by strupp-a** [identifiers-org/identifiers-org.github.io#195]
Dear all,

there are two broken links (most likely leftovers) for Retrieval and Validation Service in the "Advanced search" section on [Web services documentation](https://docs.identifiers.org/articles/services.html). The sentence explains that they are old.

[Retrieval Service](https://ebi.identifiers.org/search/)
[Validation Service](https://ebi.identifiers.org/search/)

Best,
Annika

![Screenshot from 2022-02-22 16-21-19](https://user-images.githubusercontent.com/90028232/155164891-bd3edfd3-01a7-4ace-b803-c1774f9a88f6.png)

**Comment by renatocjn** [comment]
Thank you, this was removed on the recent documentation update.
