### ISSUE TITLE
Resolution of uberon terms is broken

### ISSUE THREAD

**Issue by pwrose** [identifiers-org/identifiers-org.github.io#197]
uberon terms do not resolve. Example from: https://registry.identifiers.org/registry/uberon

https://identifiers.org/UBERON:0008203

**Comment by cthoyt** [comment]
Hi @pwrose while you wait for a response from the Identifiers.org team, you can use the Bioregistry as a drop-in replacement https://bioregistry.io/UBERON:0008203 which itself piggybacks on the OBO PURL system and redirects to http://purl.obolibrary.org/obo/UBERON_2005080

To see all of the possible URIs for this UBERON entry, check http://bioregistry.io/reference/UBERON:0008203

**Comment by renatocjn** [comment]
I have adjusted the registry to point to OLS now.
