### ISSUE TITLE
example on articles/docs/identification_scheme does not resolve

### ISSUE THREAD

**Issue by Schmoho** [identifiers-org/identifiers-org.github.io#199]
```
https://identifiers.org/ols/taxonomy/9606
-> INVALID resolution request for 'ols/taxonomy/9606', due to 'Resolution request 'ols/taxonomy/9606' is NOT ABOUT A NAMESPACE; INVALID Compact Identifier resolution request for 'ols/taxonomy/9606''
```
from https://docs.identifiers.org/articles/docs/identification_scheme.html

This is unfortunate, but also raises the question if there is some documentation about errors codes available.
Searching for googleable fragments of this particular response was unsuccessful for me.

**Comment by renatocjn** [comment]
This seems to be a bug with the resolver. It should work but it isn't. I will add this to the developer queue. Thank you for bringing this to our attention.

For now, I would recommend that you use the following link which is closer to the format of compact IDs that we mainly serve.
https://identifiers.org/ols/taxonomy:9606

**Comment by renatocjn** [comment]
The documentation page was recently updated. Thank you for letting us know.
