### ISSUE TITLE
Regex for BioSample doesn't validate example

### ISSUE THREAD

**Issue by athalhammer** [identifiers-org/identifiers-org.github.io#203]
I'm referring to the regex:

`^SAM[NED](\w)?\d+$`

in

https://registry.identifiers.org/registry/biosample

that can't match `SAMEA2397676` due to the second A (`SAME-->A<--2397676`) in the LUI

**Comment by cthoyt** [comment]
Hi @athalhammer, you might have noticed from the issue tracker that the Identifiers.org isn't really able to respond anymore. I'd suggest checking out the Bioregistry project (https://github.com/biopragmatics/bioregistry and https://bioregistry.io) for something similar that's being actively maintained and encourages community feedback.

With respect to your question, I think this works alright on Identifiers.org with https://identifiers.org/biosample:SAMEA2397676 as their page suggests - the `A` that you're pointing out in your comment seems to get matched to `(\w)?` which lets you have an optional letter following the `SAME` before the `2397676`.

This also works fine on the Bioregistry at https://bioregistry.io/biosample:SAMEA2397676

**Comment by athalhammer** [comment]
Thanks @cthoyt, you are completely right! I misinterpreted the  optional`\w` character. Thanks also for all the additional pointers!

**Comment by cthoyt** [comment]
@athalhammer Please feel free to get in touch on the Bioregistry issue tracker or @ me if you find that something's missing from either service! I am not myself affiliated with Identifiers.org but am one of the developers/maintainers of Bioregistry. We also just put a preprint last week (https://www.biorxiv.org/content/10.1101/2022.07.08.499378v2) 🚀
