### ISSUE TITLE
WikiPathways license is now CCZero

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#205]
The current description of WikiPathways in the registry still lists the data license as CC-BY, but we switched to CCZero some time ago. Please update the description to:

```
WikiPathways is a resource providing an open and public collection of pathway maps created and curated by the community in a Wiki like style. All content is under Creative Commons Zero.
```

Or leave out the "All content" line.

**Comment by cthoyt** [comment]
@egonw this information is also out of date in the Bioregistry. Would you consider submitting a PR there, or would you like me to take care of it?

**Comment by egonw** [comment]
I wasn't sure a pr to Bioregistry would not get overwritten. But, yes, can do that

**Comment by cthoyt** [comment]
The Bioregistry pulls metadata from many sources, but first and foremost allows us to override anything we deem necessary, such as in the case when it's not possible/fast enough to ask the metadata to get fixed upstream

**Comment by egonw** [comment]
Well, this was clearly out fault for not notifying them earlier.

**Comment by renatocjn** [comment]
The description has been updated.
