### ISSUE TITLE
wrong pattern for DOI 

### ISSUE THREAD

**Issue by wouteraddink** [identifiers-org/identifiers-org.github.io#207]
The  LUI pattern for DOIs seems wrong: https://registry.identifiers.org/registry/doi gives ^(doi\:)?\d{2}\.\d{4}.*$ but the DOI handbook does not specify any length for the registrant code in the prefix. For instance this is a valid DOI:
https://doi.org/10.21/FQSQT4T3 where the registrant code is 2 digits instead of 4.

**Comment by cthoyt** [comment]
Hi @wouteraddink, while you wait for the Identifiers.org team to respond, we have already made the corresponding update in  biopragmatics/bioregistry#556. It will be reflected on https://bioregistry.io/registry/doi after the nightly build.

**Comment by renatocjn** [comment]
Thank you for pointing out that mistake. I updated it to ^(doi\:)?10\.\d+/.*$
