### ISSUE TITLE
Update https://registry.identifiers.org/registry/combine.specifications resource

### ISSUE THREAD

**Issue by matthiaskoenig** [identifiers-org/identifiers-org.github.io#211]
Hi all, 
I would be the new maintainer of the combine.specifications resource.
I am one of the COMBINE coordinators at https://combine-org.github.io/people/

I would have to update the URL of the resource urgently to point to
`https://github.com/combine-org/combine-specifications/blob/main/specifications/{$id}.md`
Currently none of the https://identifiers.org/combine.specifications links resolves due to migration of the webpage and the specification resources.

Please let me know how I can update the resource and become a maintainer.
Best Matthias

**Comment by matthiaskoenig** [comment]
Hi all,
is there any way to resolve this? This is urgent because all the links are broken.
Best Matthias

**Comment by renatocjn** [comment]
Hello Matthias,

We handle entry updates through the support e-mail identifiers-org@ebi.ac.uk
We rather keep the GitHub issues to development discussions.

You will shortly be receiving an email from me to handle this.

Best regards.
