### ISSUE TITLE
Include Metabolomics Workbench?

### ISSUE THREAD

**Issue by tlemberger** [identifiers-org/identifiers-org.github.io#212]
Please include https://www.metabolomicsworkbench.org/ in the registry.

Example dataset:
identifier for study: ST002025
resolves to: https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST002025&StudyType=MS&ResultType=1

identifier for project: PR001287
https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Project&ProjectID=PR001287

**Comment by renatocjn** [comment]
Dear Thomas, 

Please submit a prefix request through our website https://registry.identifiers.org/prefixregistrationrequest for it to be evaluated by our curation team.

It seems to me that you will need two prefixes, one for studies and one for projects. Feel free to email identifiers-org@ebi.ac.uk or consult our documentation pages at docs.identifiers.org in case of any doubt.

We do not take registration requests through GitHub issues. We are trying to keep these for development discussion.
