### ISSUE TITLE
BioStudies pattern

### ISSUE THREAD

**Issue by usarkans** [identifiers-org/identifiers-org.github.io#215]
Hi! - currently the pattern for BioStudies is
^S-[A-Z]{4}[A-Z\d\-]+$

We realized we sometimes have underscores as well - so, could you change this to
^S-[A-Z]{4}[A-Z\d\-\_]+$

please.

**Comment by cthoyt** [comment]
can you give an example of an identifier with an underscore?

**Comment by renatocjn** [comment]
@usarkans I agree with Charles, could you provide an example of such ID?

**Comment by usarkans** [comment]
Looks like my earlier reply via e-mail got lost. An example is https://www.ebi.ac.uk/biostudies/SourceData/studies/S-SCDT-10_15252-MSB_202211037
