### ISSUE TITLE
ISBN resolving not working properly 

### ISSUE THREAD

**Issue by andreas-c-hofmann** [identifiers-org/identifiers-org.github.io#217]
Hi there, 

I want to resolve the ISBN "978-3-643-14423-2" (cf. https://portal.dnb.de/opac/simpleSearch?query=978-3-643-14423-2). In doing that I observed the following problems: 

1. If I resolve the ISBN by typing it in, I get to https://identifiers.org/resolve?query=isbn:978-3-643-14423-2, which will be - perfectly - offering two sources (isbndb and worldcat) for the identifier. 
2. If I use the in Nr. 1 given Shortcut https://identifiers.org/isbn:978-3-643-14423-2 I only (!) get to isbndb. Ignoring the fact, that isbndb contains less title than worldcat, the ISBN is retrievaled wrong and cut. 
Type in: https://identifiers.org/isbn:978-3-643-14423-2 ==> https://isbndb.com/book/978

Many thanks for your work!
Andreas

**Comment by renatocjn** [comment]
Seems like there is an issue with how the query is handled by isbndb after we forward it. You can see in the [backend](http://resolver.api.identifiers.org/isbn:978-3-643-14423-2) that the resolved URL contains the full ISBN ID. I also checked encoding the ID and it doesn't seem to work. I will look into that, thank you for bringing this up to us.

What I can propose to you now is to use one of the following URLs for this specific book:
One that uses ISBN-10: identifiers.org/isbn:3643144237
One worldcat provider code: identifiers.org/worldcat/isbn:978-3-643-14423-2

**Comment by renatocjn** [comment]
Hello,

I got in touch with ISBNdb and they informed me that we are suppose to work without dashes. If you need to use dashes, use the WorldCat provider code as it seems to work in that format.

- [identifiers.org/isbn:9783643144232](http://identifiers.org/isbn:9783643144232)
- [identifiers.org/worldcat/isbn:978-3-643-14423-2](http://identifiers.org/worldcat/isbn:978-3-643-14423-2)
