### ISSUE TITLE
Does this only apply to the life sciences?

### ISSUE THREAD

**Issue by ZanderZhao** [identifiers-org/identifiers-org.github.io#220]
Thank you very much for your work, please this is only applicable to the field of life sciences, I want to submit a dataset on the field of solar physics, can it? I have submitted the prefix 'nlfff' application, because it is not clear how it works before, submit  some applications containing errors, please take the last one, thank you!

**Comment by renatocjn** [comment]
Identifiers.org is open to any kind of research data. We simply are currently closer to life sciences. That is why we strongly recommend that submissions provide references associated with their work to show the interest of the community on the subject.

You will be happy to see that your request was accepted. For future reference, adjustments to requests are done by curators after discussion with the requesters. Do not submit requests to the same prefix several times.

Best regards.

**Comment by ZanderZhao** [comment]
Thank you very much, just received an email, now you can access it, before not quite understand the mode work, now understand. Now here is a record of the problems encountered and the method, to facilitate the researchers who encountered this problem later.

+ 0. This system is not limited to the field of study,
+ 1. This system model is similar to link forwarding, using the premise that there is a website that can create a separate page for each sample, and then mapped to each sample according to certain rules.
+ 2. Currently (20230203) registration is not visible after submission of the submission record, the success of the submission will receive an email, audit problems will also receive an email, there is a work order link inside the email, the visitor should not be able to log in, you can contact through email.
+ 3. Mark the citation can help them review faster, especially across the field.
+ 4. If there is an error after submission they will contact you, do not have to repeat the submission, and there are problems can contact them through identifiers-org[at]ebi.ac.uk, I have always thought that this is a robot mailbox, may not receive incoming mail, now it seems that it should be received
+ 5. If you don't get the letter temporarily, you can wait, they may be on holiday.

I hope it will be helpful to the later users, and thanks a lot to Identifiers.org Team.

**Comment by renatocjn** [comment]
Hello,

Thanks you for giving your account of your experience, hopefully it was not too bad. 

Just to be sure, in point ii, you mention "registration is not visible after submission", maybe you couldn't find it but your namespace is registered here at <https://registry.identifiers.org/registry/nlfff>. You are now able to use links such as:
- <https://identifiers.org/nlfff:345201101230312003>
- <https://identifiers.org/nlfff:7334201901261600003>
- <https://identifiers.org/nlfff:7334201901261424003>

Let me know if you still have any issues.

**Comment by ZanderZhao** [comment]
Hi, thanks a lot for replying again, no more problems now, I can now access it normally. What I meant to express was, "After submitting an application, it is not possible to find the submission record inside the system until the registration application is approved, i.e. after submission, but before the review and approval, it is temporarily impossible to view or change the submitted application". There may be some problems with the previous expression. ^-^

**Comment by renatocjn** [comment]
Great :)
