### ISSUE TITLE
New term request - HCC1937 cell line

### ISSUE THREAD

**Issue by kalpanaps** [identifiers-org/identifiers-org.github.io#223]
Requesting new term from HCC1937, which is cell line isolated from a primary ductal carcinoma. Further details can be found at https://www.cellosaurus.org/CVCL_0290; https://lincs.hms.harvard.edu/db/cells/50212/

Thanks!

**Comment by renatocjn** [comment]
Hello @kalpanaps,

The term can already be accessed via:
- https://identifiers.org/clo:0003645
- https://identifiers.org/lincs.cell:LCL-1331
- https://identifiers.org/cellosaurus:CVCL_0290

I don't think we have an entry for the [Library of Integrated Network-based Cellular Signatures](https://lincs.hms.harvard.edu/db/), it doesn't seem to use the same IDs as [lincs.cell](https://registry.identifiers.org/registry/lincs.cell). I guess these are separate entities. @cthoyt, is there an entry for this in bioregistry?

**Comment by kalpanaps** [comment]
Thank you, and sorry for missing this earlier
email: ***@***.***

**Comment by renatocjn** [comment]
No worries, glad to help.

**Comment by cthoyt** [comment]
I hadn't looked carefully into the differences between the HMS and Miami LINCS sites - I added several additional HMS prefixes to the Bioregistry in https://github.com/biopragmatics/bioregistry/pull/736 to reflect those differences
