### ISSUE TITLE
Update the EPD entry

### ISSUE THREAD

**Issue by smoretti** [identifiers-org/identifiers-org.github.io#224]
Hi

could you update the epd entry in identifiers.org?

The `URL Pattern` should now be:
https://epd.expasy.org/cgi-bin/epd/query_result.pl?out_format=NICE&Entry_0={$id}

The `Home URL` should now be:
https://epd.expasy.org/epd/

Thanks

**Comment by renatocjn** [comment]
Done, thank you for letting us know.

**Comment by smoretti** [comment]
Thanks
The URL Pattern is the right one, but when I click on https://identifiers.org/epd:TA_H3 it is not
