### ISSUE TITLE
Update the bgee.gene entry

### ISSUE THREAD

**Issue by smoretti** [identifiers-org/identifiers-org.github.io#226]
Hi

could you update the bgee.gene entry?

The **description** is now:
`Bgee is a database to retrieve and compare gene expression patterns in multiple species, produced from multiple data types (bulk RNA-Seq, scRNA-Seq, Affymetrix, in situ hybridization, and EST data). This collection references genes in Bgee.`

The **Local Unique Identifier (LUI) pattern** and **Prefix embedded in LUI** are now:
`^[A-Za-z0-9]+$`

The **URL Pattern** is now:
`https://www.bgee.org/gene/{$id}/`

The **Home URL** is now:
`https://www.bgee.org/`

Thanks

**Comment by renatocjn** [comment]
This is done, please have a look and let me know if it's ok.

**Comment by smoretti** [comment]
Everything looks good.
Thanks
