### ISSUE TITLE
Entity resolution does not work, with a JS error

### ISSUE THREAD

**Issue by chrishmorris** [identifiers-org/identifiers-org.github.io#228]
e.g. in the resolution tab type "DOID:4" and click "resolve". Nothing happens, except in the Javascript console:

```
/index.0096cb57.js:31 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.$i (/index.0096cb57.js:31:63607)
    at Object.S (/index.0096cb57.js:21:8102)
    at st (/index.0096cb57.js:112:1396)
    at ct (/index.0096cb57.js:112:1486)
    at xn.handleSearch (/index.0096cb57.js:112:33164)
    at /index.0096cb57.js:112:33084
    at Object.Qe (/index.0096cb57.js:31:17728)
    at et (/index.0096cb57.js:31:17882)
    at /index.0096cb57.js:31:37768
    at Xr (/index.0096cb57.js:31:37862)
```
Same on Chromium and Firefox.

**Comment by renatocjn** [comment]
Sorry for the delay. I missed the notifications for this issue.

I guess you mean in the search bar under "Resolve a Compact Identifier" on the right side.

We are aware of this issue, we have other tasks to handle at the moment but will get to this as soon as we can. Sorry for the inconvenience.

**Comment by renatocjn** [comment]
This should be fixed now. I will leave the issue open since I also realized that the button on the registry search bar is also not working. I will fix that soon.
