### ISSUE TITLE
Update urlPatterns for Ontology through OLS to OLS4

### ISSUE THREAD

**Issue by matthiaskoenig** [identifiers-org/identifiers-org.github.io#231]
The OLS3 will stop working at the end of the month and currently has a lot of issues (https://www.ebi.ac.uk/ols). E.g. the webpage is down for the last few days, and maintenance will stop in a few days.
The urlPatterns should be switched to the new OLS4 https://www.ebi.ac.uk/ols4

I.e. things such as 
```
"urlPattern": "https://www.ebi.ac.uk/ols/ontologies/teddy/terms?short_form={$id}",
```
should now be
```
"urlPattern": "https://www.ebi.ac.uk/ols4/ontologies/teddy/terms?short_form={$id}",
```
Same for home URL: `https://www.ebi.ac.uk/ols/ontologies/teddy` -> `https://www.ebi.ac.uk/ols4/ontologies/teddy`
This affects all OLS resources.

**Comment by matthiaskoenig** [comment]
This affects only a handful of urls, many already have been updated. See screenshot attached:
![Screenshot from 2023-10-08 15-00-01](https://github.com/identifiers-org/identifiers-org.github.io/assets/900538/2bd0ff5f-3362-46b6-9755-2aa7ce61bd2b)

I.e. `bao`, `teddy`, `obi`, `edam`, `vario`, `mamo`, `eo`, `ordo`, `probonto`, `nmrcv`

**Comment by renatocjn** [comment]
Hi,
I have a GH issue with the OLS 4 team and I will be updating the remaining URLs soon. Here is the issue: EBISPOT/ols4#388

Could you provide the location where you saw that OLS 3 will be offline by the end of the month?

**Comment by matthiaskoenig** [comment]
Not be offline, but no longer maintained. But from the outage the last days
it can be assumed this won't work well in the future. I assume/hope they
shut it down and redirect to OLS4. Information was on the OLS3 page which
was not reachable yesterday.

**Comment by renatocjn** [comment]
These were updated a while ago, I forgot to close this issue. Please reopen if any URL pattern still uses OLS
