### ISSUE TITLE
Request to change of URL Pattern for nmdc prefix?

### ISSUE THREAD

**Issue by dwinston** [identifiers-org/identifiers-org.github.io#233]
Hi, I registered the prefix for `nmdc`: https://registry.identifiers.org/registry/nmdc

The URL Pattern is currently `https://drs.microbiomedata.org/objects/{$id}`, but I would like to change it to be `https://w3id.org/nmdc/{$id}`.

How can I do this? I don't see an obvious affordance at <https://registry.identifiers.org/registry/nmdc>.

/cc @turbomam

**Comment by dwinston** [comment]
when I log in, I do see a "Curation Dashboard", but this does not lead to an editable version of <https://registry.identifiers.org/registry/nmdc>, just the normal read-only version.

**Comment by renatocjn** [comment]
Hello @dwinston,
Currently, curation is done by our curation team. I will quickly check your new pattern and let you know about that. If everything is fine, I will update it myself.
The login link in identifiers.org is for curators. Anyone can create an account but only people with specific roles can edit entries.

**Comment by renatocjn** [comment]
Hi, a few questions
- Is the new URL still managed by Lawrence Berkeley National Laboratory?
- Seems like changing the URL will change it from DRS objects to a landing page. Do you know if the DRS endpoint going to become offline?
- Are you sure the whole data is available in the new URL? The sample URL is not available with your pattern.
  - https://drs.microbiomedata.org/objects/6m4e-1vbv-03
  - https://w3id.org/nmdc/6m4e-1vbv-03

We might want to keep both URL patterns as separate resources. Then, if you want to, [you can resolve to a specific resource using provider codes](https://docs.identifiers.org/pages/resolving_mechanisms.html).

**Comment by renatocjn** [comment]
@dwinston any change on the situation?

**Comment by dwinston** [comment]
Hi @renatocjn , 

> Is the new URL still managed by Lawrence Berkeley National Laboratory?

Yes

> Seems like changing the URL will change it from DRS objects to a landing page. Do you know if the DRS endpoint going to become offline?

It's not going offline. Rather we want to point to a gateway that can more dynamically route requests to one of: (1) our static schema element landing pages, (2) our data portal landing pages (if a published -- not draft -- identifier of a particular type -- for us, a "study" or a "biosample"), or (3) a more generic DRS object. Thus, we want to use [w3id.org/nmdc](https://github.com/perma-id/w3id.org/tree/c5dd7916190e5cbc27c2462feaa5bdbecd0aa90a/nmdc) to manage a dynamic Apache config for these cases. However,

> Are you sure the whole data is available in the new URL? The sample URL is not available with your pattern. 

This is not currently the case. We need to install a new config at the w3id.org repo. I understand your reluctance to switch over until we can demonstrate the new functionality.

@turbomam , we should do this ASAP so that @renatocjn can proceed.

**Comment by dwinston** [comment]
Thanks. Waiting on merge of https://github.com/perma-id/w3id.org/pull/3731, then will be ready to test again.

**Comment by renatocjn** [comment]
Hello @dwinston,
It looks to be working and it seems that the gateway displays the same information for the sample DRS. So I can just change the URL pattern for the existing resource. Could you make sure the rest of the information stays the same? Especially the  LUI pattern since you mention different types of data are also resolvable via this gateway.

**Comment by dwinston** [comment]
@renatocjn great! Yes, all else (including the LUI) remains the same.

**Comment by renatocjn** [comment]
Done. Let me know if you need anything else.
