### ISSUE TITLE
3dmet identifier URIs don't redirect properly

### ISSUE THREAD

**Issue by carlosvega** [identifiers-org/identifiers-org.github.io#238]
Even the example in identifiers.org does not work. https://registry.identifiers.org/registry/3dmet 

https://identifiers.org/3dmet:B00162

Best,

Carlos

**Comment by cthoyt** [comment]
I'm pretty sure this website has been down for some time

**Comment by renatocjn** [comment]
Sorry for the delay. It indeed seems to be down. Fair sharing also has it as deprecated: https://fairsharing.org/FAIRsharing.5ab0n7. I will mark it as deprecated just in case. If anyone has information on what happened to it, let me know and I can add to it.

@carlosvega, you can still use identifiers.org links to it, but the resolved URL won't be of use.
