### ISSUE TITLE
RFAM url needs update

### ISSUE THREAD

**Issue by EliotRagueneau** [identifiers-org/identifiers-org.github.io#240]
Hi identifiers.org team,

We noticed that RFAM have updated their URL pattern, which makes the current URL you're sending back for their identifiers non secured by HTTPS:

- Current URL:
  - https://rfam.xfam.org/family/RF01518
- New URL 
  - https://rfam.org/family/RF01518

Would be great if that could be updated 😄

**Comment by EliotRagueneau** [comment]
No, not at all, just a user who noticed one of my script failed because RFAM URL from identifiers.org wasn't working with HTTPS.
Of course, I think it's better to get contact from someone within RFAM to make sure what I said is correct.

**Comment by renatocjn** [comment]
Hi @EliotRagueneau,

You are right, they added a redirect from the old URL to the new one. The old URL also has an SSL certificate issue when using HTTPS.

I updated the home URL and URL pattern. Thank you for bringing this up to us.
