### ISSUE TITLE
HGNC Gene Groups URL pattern is broken

### ISSUE THREAD

**Issue by njoannin** [identifiers-org/identifiers-org.github.io#244]
Looking at https://registry.identifiers.org/registry/hgnc.genegroup

The URL pattern listed is: https://www.genenames.org/cgi-bin/genefamilies/set/{$id} but this results in a 404 page.

The correct URL pattern seems to be: https://www.genenames.org/data/genegroup/#!/group/{$id}

Would it be possible to update the pattern to the correct one?

**Comment by renatocjn** [comment]
Thank you for bringing this to us, I have updated the pattern.
