### ISSUE TITLE
Please remove the https in the URL Pattern of the uniprot records when pointing to purl.uniprot.org

### ISSUE THREAD

**Issue by JervenBolleman** [identifiers-org/identifiers-org.github.io#245]
Hi

The url pattern

	https://purl.uniprot.org/uniprot/{$id}

should be

        http://purl.uniprot.org/uniprot/{$id}

in the record uniprotkb.

In the record uniprotkb.isoform

the url pattern on our side should be

     http://purl.uniprot.org/isoforms/{id}

Thank you,
Regards,
Jerven

PS,  Found when testing https://sparql.api.identifiers.org/sparql/ very nice that it is back, although the help page deserves some love and updates.

**Comment by JervenBolleman** [comment]
@renatocjn it is not that they don't work. It is that the global identifier for uniprot records is without https.

The query I used for testing at  the [uniprot sparql endpoint](https://sparql.uniprot.org/sparql) is

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT
?alternate
WHERE
{
  SERVICE <https://sparql.api.identifiers.org/sparql> {
     <https://purl.uniprot.org/uniprot/P07500> owl:sameAs ?alternate .
  }
}
```

But that is bad because the identifier on our side that works is 

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT
?alternate
WHERE
{
  SERVICE <https://sparql.api.identifiers.org/sparql> {
     <http://purl.uniprot.org/uniprot/P07500> owl:sameAs ?alternate .
  }
}
```

**Comment by renatocjn** [comment]
Hi, thank you for the examples. I will try to check things. 

I do not know the meeting, unfortunately. When I joined, the previous developer already wasn't familiar with the internal workings of this endpoint. It was migrated with the rest of the services a while back and probably there was a change in its URL. I'm personally not very familiar with SPARQL and I don't know how it was initially made.

[We have a project to work on this and some other tasks in the ELIXIR BioHackathon](https://github.com/elixir-europe/biohackathon-projects-2024/blob/main/13.md). We would love any help we can get. It would be nice to take input from the community on how this is being used.

The current plan is to use something like ontop (https://ontop-vkg.org/) to keep the dataset up-to-date and make it compatible with schemas such as DCAT (https://www.w3.org/TR/vocab-dcat-3/), VOiD (https://www.w3.org/TR/void/), and bioschemas.org.

**Comment by JervenBolleman** [comment]
@renatocjn let's open a new issue on the SPARQL topic. While I wait for the uniprot identifiers to be corrected.

**Comment by renatocjn** [comment]
@JervenBolleman, has it been solved?

**Comment by JervenBolleman** [comment]
Yes. and we can use it on our sparql endpoint.

```sparql
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT 
    ?protein 
    ?otherIdentifier
WHERE {
  BIND(uniprotkb:P00750 AS ?protein)
  SERVICE <https://sparql.api.identifiers.org/sparql> {
    ?protein owl:sameAs ?otherIdentifier .
 }
}
```

**Comment by renatocjn** [comment]
Perfect, thank you
