### ISSUE TITLE
Do you plan to add RInChI?

### ISSUE THREAD

**Issue by smoretti** [identifiers-org/identifiers-org.github.io#247]
Do you plan to add RInChI and RInChIKey in identifiers.org?

Also, the InChIKey regex should have **$** at the end. A string longer than `[A-Z]{14}-[A-Z]{10}-[A-Z]` has no sense for InChIKey.

**Comment by renatocjn** [comment]
We mostly add namespaces upon requests by users, would you be able to make a request for RInChI and RInChIKey through our [online form](https://registry.identifiers.org/prefixregistrationrequest)? That way we have a starting point for it.

I will have a look at the regex for InChIKey.

**Comment by smoretti** [comment]
Need to find a resource resolving RInChI/RInChIKey first
Thanks

**Comment by renatocjn** [comment]
I updated the pattern. I will close this issue but feel free to make requests for RInChI and RInChIKey.
