### ISSUE TITLE
Link / Endpoint health / checking mechanism

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/identifiers-org.github.io#3]
It would be good to have another component in the infrastructure that offers health checks for given URLs, this way, everytime we resolve a Compact ID, we could also collect some information on its endpoints, e.g. if they are reachable, HTTP 200 OK, etc.

**Comment by mbdebian** [comment]
A first version of a Link Checker service that computes reliability scores on providers and resources is coming up !

**Comment by cthoyt** [comment]
@mbdebian does this feature still exist?
