### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/identifiers-org.github.io#6]
Look into the possibility of publishing identifiers.org artifacts in Maven Central

**Comment by mbdebian** [comment]
For this one, it looks like we need to go this way
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by mbdebian** [comment]
I just submitted the application for access to Maven Central ^_^

**Comment by sarala** [comment]
Great work!

**Comment by mbdebian** [comment]
I submitted the first release of libapi, I'm now waiting for Maven Central to synchronize and index the new artifact.

**Comment by mbdebian** [comment]
OMG! We're in Maven Central!!!!
