### ISSUE TITLE
The new design looks great

### ISSUE THREAD

**Issue by chrisgorgo** [identifiers-org/identifiers-org.github.io#62]
This is not really an issue, but I just wanted to drop by and say I really like the looks of the new design. Great work!

**Comment by javfg** [comment]
Thanks a lot for the support! You made my day.

We are still working towards improving many design aspects. Stay tuned for updates!

**Comment by mbdebian** [comment]
OMG! Thank you so much!!!
We are working really hard to make identifiers.org the best possible experience for our users!
