### ISSUE TITLE
compact identifier for antibody registry

### ISSUE THREAD

**Issue by bandrow** [identifiers-org/identifiers-org.github.io#63]
Hi the compact identifier for the antibodyregistry record should be AB_
This is how antibody records are cited by authors, e.g., 
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=RRID%3AAB_2298772&btnG=

**Comment by mbdebian** [comment]
Hi @bandrow ,
Thanks a lot for submitting this feedback.
This has now been fixed.
Best Regards,
Manuel

**Comment by bandrow** [comment]
This part is not fixed: 

The compact identifier ***USED*** in the literature is not antibodyregistry:12345 the compact identifier used in the literature is RRID:AB_12345; I gave the example of an antibody identifier that is used in 460 papers; please do not recreate this for me because journals are already actually enforcing the RRID:AB_ version. I don't need a competing compact identifier scheme that nobody uses but just makes the world confused. 
Look here for how the compact identifier is used in the scientific literature: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=RRID%3AAB_2298772&btnG=

this is wrong on identifiers.org
Prefix | antibodyregistry
-- | --
Registry URI | https://registry.identifiers.org/registry/antibodyregistry
Sample URL | https://identifiers.org/antibodyregistry:493771
Sample Compact identifier | antibodyregistry:493771
Sample ID (LUI) | 493771
