### ISSUE TITLE
GOLD mismatch?

### ISSUE THREAD

**Issue by jjkoehorst** [identifiers-org/identifiers-org.github.io#68]
I think the regex is wrong or?

`Your compact identifier appears to be incorrect: The local id Gi03924  does not match the pattern ^[Gi|Gc]\d+$.`

**Comment by mbdebian** [comment]
Thanks for reporting this @jjkoehorst 
We are getting in touch with the resource owner to provide up to date information on this.
Best Regards,
Manuel

**Comment by mbdebian** [comment]
This is now fixed.
Thanks @jjkoehorst for reporting this.
Best Regards,
Manuel
