### ISSUE TITLE
metacyc has an incomplete pattern

### ISSUE THREAD

**Issue by Midnighter** [identifiers-org/identifiers-org.github.io#69]
The currently listed `metacyc.compound` regex pattern is `^CPD-\d{5}$`. This is incomplete as shown by the following example:

https://metacyc.org/compound?orgid=META&id=CPD0-2200

**Comment by mbdebian** [comment]
Hi @Midnighter , 
Thanks for reporting this back to us, I just wanted to say that the provider has been contacted and we are waiting for a reply with up to date information on this.
Best Regards,
Manuel

**Comment by edkerk** [comment]
I just want to add to this that this is not just a matter of changing position of the dash, as in the example given by @Midnighter. The identifier can also be e.g. `ATP` as shown here: https://metacyc.org/compound?orgid=META&id=ATP. A more accurate regex would be `^[A-Za-z0-9+_.%-:]+$`.

The same case is true for `metacyc.reaction`, examplified with `GLUCOKIN-RXN`: https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=GLUCOKIN-RXN. The same regex as above would also work for reactions.

**Comment by mbdebian** [comment]
Thanks for the additional information @edkerk , I'm still waiting for metacyc contact to get back to me on this.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
This issue is now closed due to the lack of response from the organisation responsible for metacyc information.
