### ISSUE TITLE
Registries for genomes

### ISSUE THREAD

**Issue by Midnighter** [identifiers-org/identifiers-org.github.io#70]
It seems to me that the ability of a genome (assembly) reference are missing for NCBI, GenBank, and RefSeq. An example for [Escherichia coli str. K-12 substr. MG1655](https://www.ncbi.nlm.nih.gov/assembly/GCF_000005845.2).

**Comment by mbdebian** [comment]
Dear @Midnighter ,
Thanks for your feedback.
Could you be more specific on your request?
Thanks in advance.
Kind Regards,
Manuel

**Comment by Midnighter** [comment]
When working with genome-scale metabolic models, see for example, http://bigg.ucsd.edu/models/iML1515, there is a need to unambiguously annotate the genome that was used as a basis for reconstructing the metabolic network. Identifiers.org contains namespaces for NCBI genes and proteins but not for whole assemblies such as the one linked above. Similarly, the current RefSeq pattern only allows for genes and proteins but not for entire genomes (assemblies). GenBank, another repository for genomes is not present at all.

**Comment by mbdebian** [comment]
Hi @Midnighter ,
We have considered your request and, at identifiers.org we'd like to point out that the registry contains information that life sciences resources decided to register on it, and it is not an active crawler of the data repositories, making up prefixes for everything found in the process.
I hope you find this information useful, please, don't hesitate to let us know if you'd have any other question.
Kind Regards,
Manuel

**Comment by Midnighter** [comment]
So what you're saying is that you would wait for those repositories to register themselves with Identifiers.org rather than proactively including them?

**Comment by mbdebian** [comment]
Identifiers.org offers, the life sciences community, resolution services for compact identifiers, but it is up to those resources to decide on whether they would like to enhance their FAIR metrics / score by adopting this mechanism or not.
It depends on them and their communities to find out whether this compact identifier mechanism and the services built around it by identifiers.org are of added value for them and their communities.

**Comment by Midnighter** [comment]
As an afterthought, through browsing other issues I found the [genome assembly database](https://registry.identifiers.org/registry/insdc.gca) namespace. That is exactly what I wanted but I didn't manage to find through the registry browser before.

**Comment by Midnighter** [comment]
Oh, and you do include [RefSeq](https://registry.identifiers.org/registry/refseq) now as well. :smiley:
