### ISSUE TITLE
update the info for MIR:00000711

### ISSUE THREAD

**Issue by egonw** [identifiers-org/identifiers-org.github.io#73]
It was [requested](https://github.com/NanoCommons/identifiers/issues/8) to update the location info. My original idea was that since GitHub is hosted in the USA, that should be the location.

However, based on the request and the notion that the ERM is currently coordinated by me (Maastricht University), I suggest to update the following:

- Location: Maastricht, The Netherlands
- Organization: Maastricht University
- ROR id: https://ror.org/02jz4aj89

**Comment by mbdebian** [comment]
Thanks @egonw , I'll have a look at this.

**Comment by mbdebian** [comment]
Thanks for the request @egonw , and sorry for the delay, this has now been solved.
Kind Regards,
Manuel
