### ISSUE TITLE
search field in "Browse the registry" page

### ISSUE THREAD

**Issue by piotr-gawron** [identifiers-org/identifiers-org.github.io#75]
Search field on this page: https://registry.identifiers.org/registry is not intuitive:
* first it's limited only to the prefix column (name and description are ignored): I wanted to find entry for "omim" (which is entry name), but couldn't find it. I had to type "mim"
* second - this field is case sensitive: "mim" is different than "MIM"

**Comment by mbdebian** [comment]
Thanks a lot for your feedback @piotr-gawron , we'll pass your suggestion on to our UX team.
Please, don't hesitate to get in touch if you have any other query.
Kind Regards,
Manuel
