### ISSUE TITLE
Problems resolving SBO terms

### ISSUE THREAD

**Issue by cjmyers** [identifiers-org/identifiers-org.github.io#77]
These terms used by SBOL, no longer resolve:

http://identifiers.org/biomodels.sbo/SBO:0000169

They appear to be replaced with:

http://identifiers.org/sbo/SBO:0000169

Can you make the former alias to the later?  This is a huge problem for SBOL, since we have been using the former in SBOL for several years now, and we are stuck now with identifiers that do not resolve.

**Comment by mbdebian** [comment]
Hi @cjmyers ,
Thanks for reaching out and providing your feedback.
Effectively, "SBO" is a namespace in identifiers.org, ant the URL 'http://identifiers.org/biomodels.sbo/SBO:0000169' would be requesting the resolver to resolve compact identifier 'SBO:0000169' to provider 'biomodels.sbo', the problem here, is that no provider in 'SBO' namespace is registered with provider code 'biomodels.sbo'.
Would be able to give us more details on what 'http://identifiers.org/biomodels.sbo/SBO:0000169' should resolve to?
Thanks in advance for your feedback on this @cjmyers .
Kind Regards,
Manuel

**Comment by cjmyers** [comment]
Hi @mbdebian, 
This used to resolve to the same location that the following now resolves to:

http://identifiers.org/sbo/SBO:0000169

Namely,

https://www.ebi.ac.uk/sbo/main/SBO:0000169

At some point, you changed it so that it no longer resolves to that anymore.  We relied upon this identifier:

http://identifiers.org/biomodels.sbo/SBO:0000169

being resolvable.  The SBOL specification used this URI scheme because we were told it would always be resolvable rather than using the EBI link directly. 

Could you please restore this link, so we don't have a ton of unresolvable links in SBOL data.
Thanks,
Chris

**Comment by mbdebian** [comment]
Hi @cjmyers ,
There are several ways identifiers.org resolution services:
- http://identifiers.org/**<<compact:identifier>>**
- http://identifiers.org/**<<provider_code>>**/**<<compact:identifier>>**

Identifiers.org registry has the advantage of allowing multiple providers per namespace, enabling, this way, a failover / choice mechanism.

Providers reliability information is internally collected over time, and it plays a role in the resolver decision making when resolving a compact identifier request.

To take full advantage of this, we encourage our users to use the stable URL **'http://identifiers.org/<compact:identifier>'**.

In the case a user would like the resolver to '**force**' the resolution to a particular provider, a '**provider code**' may be supplied in the URL, e.g. 'http://identifiers.org/biomodels.sbo/SBO:0000169' is requesting the resolver to resolve compact identifier '**SBO:0000169**' to provider '**biomodels.sbo**'.

This way of requesting compact identifier resolution does not count on the failover / multiple choice mechanism mentioned above, and it results on not stable URLs, as providers may no longer be in service, or they may choose to change their provider code.

In the case of SBO, the resolved URL ‘https://www.ebi.ac.uk/sbo/main/SBO:0000169’ you mention in your comment, is associated to a resource with provider code ‘**ebi**’.

After a conversation with Biomodels team, there seem to be no problem on changing this provider code to “biomodels.sbo”, as a _temporary fix_ for those legacy URLs, but in the long term, we really encourage our users to make use of identifiers.org stable and reliable URLs for compact identifier resolution.

Thanks again for your feedback, and please, don’t hesitate to reach out to us in case you have any other question.

Kind Regards,
Manuel

**Comment by cjmyers** [comment]
Thanks.  It is working again.  I will suggest for SBOL3 that we move to compact identifiers in the future.

Chris
