### ISSUE TITLE
Identifiers.org link for Assembly GCF accession IDs

### ISSUE THREAD

**Issue by AlexandraPhil** [identifiers-org/identifiers-org.github.io#78]
Hi, 

My name is Alexandra Philiastides and I work as a curator for the journal Scientific Data.
I am currently unable to create an identifiers.org link for https://www.ncbi.nlm.nih.gov/assembly/GCF_000148765.1/ (This is in NCBI Assembly)

The link which I have created: https://identifiers.org/ncbi/insdc.gca:GCF_000148765.1 does not resolve.

Could you please assist me with this and make sure I can create an identifiers.org link for this url: https://www.ncbi.nlm.nih.gov/assembly/GCF_000148765.1/ (as well as for other GCF urls)?

Many thanks,

Kind regards,

Alexandra Philiastides

**Comment by mbdebian** [comment]
Hi @AlexandraPhil ,
Thanks a lot for reaching out to us with this issue.

I've had a look at the namespace [insdc.gca](https://registry.identifiers.org/registry/insdc.gca) where this prefix is described, and, effectively, the IDs in this namespace are defined as a string that starts with 'GCA', but, by looking at the NCBI landing page for your sample RefSeq ID [GCF_000148765.1](https://www.ncbi.nlm.nih.gov/assembly/GCF_000148765.1), I can see it makes sense it should be resolvable.

So then, I decided to check the [NCBI Genome Assembly Model](https://www.ncbi.nlm.nih.gov/assembly/model/) and it is clear that RefSeq IDs (GCF_...) are supported and resolved, so I've made the corresponding update in the namespace definition and the changes are now on-line in the resolution services.

I'd like to thank you again for reporting this, and also, encourage you to use our stable compact identifier resolution URL to get full advantage of the capabilities of our resolution services, i.e. we recommend using **https://identifiers.org/insdc.gca:GCF_000148765.1**, with no _provider code_ information, rather that the more specific, and not that stable URL, **https://identifiers.org/ncbi/insdc.gca:GCF_000148765.1**, that includes the _provider code_ for **NCBI** resource within the namespace.

Kind Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Hi Manuel,

Thanks for the quick response and the useful information.

Note that the new link you provided : https://identifiers.org/insdc.gca:GCF_000148765.1<https://urldefense.proofpoint.com/v2/url?u=https-3A__identifiers.org_insdc.gca-3AGCF-5F000148765.1&d=DwMCaQ&c=vh6FgFnduejNhPPD0fl_yRaSfZy8CWbWnIf4XJhSqx8&r=fAL21dH0rOqFcqclLoW5wNcMIT27gMdOiMljeGKCECyYsup1fBZxeLEfYkG_nSVT&m=gozmRp--haWPXd_QIko8zFGIiAcnj3eBevWvmWJb4Lw&s=ozevmJ1XlNZVJbqRZSfoUMqWmrUmGemOo_qy1XmfcBU&e=> directs to EBI and that’s not where these data are. The good news however, is that the link I previously provided  https://identifiers.org/ncbi/insdc.gca:GCF_000148765.1<https://urldefense.proofpoint.com/v2/url?u=https-3A__identifiers.org_ncbi_insdc.gca-3AGCF-5F000148765.1&d=DwMCaQ&c=vh6FgFnduejNhPPD0fl_yRaSfZy8CWbWnIf4XJhSqx8&r=fAL21dH0rOqFcqclLoW5wNcMIT27gMdOiMljeGKCECyYsup1fBZxeLEfYkG_nSVT&m=gozmRp--haWPXd_QIko8zFGIiAcnj3eBevWvmWJb4Lw&s=GMYtHP-_DyB_o5uf2GV73AmxwzoGscYsWty3wUlYFxg&e=> now resolves and directs to the correct landing page.

Many thanks for your help!

Best,

Alexandra
