### ISSUE TITLE
How to update a record

### ISSUE THREAD

**Issue by ivanmicetic** [identifiers-org/identifiers-org.github.io#80]
How do you update a record (namespace) details with a new interface? How do you request an ownership change for a resource that has been migrated/updated to a new institute?
Specifically I would like to update mobidb namespace and get ownership and update disprot namespace.

**Comment by mbdebian** [comment]
Hi @ivanmicetic ,
Thanks a lot for reaching out.
Right now, we have no automated (via the API or the web frontend) mechanism for requesting an update on a particular namespace, or a particular provider within a namespace, we’ll be working on these extensions in the mid-term.
But you can do it via an e-mail to our curator e-mail: [identifiers-org@ebi.ac.uk](mailto:identifiers-org@ebi.ac.uk).
Thanks again for your feedback @ivanmicetic 
Please, don’t hesitate to get back in touch if you’d have any other question.
Kind Regards,
Manuel
