### ISSUE TITLE
Human Phenotype Ontology link is broken

### ISSUE THREAD

**Issue by njoannin** [identifiers-org/identifiers-org.github.io#81]
https://identifiers.org/hp:0000118 gets an invalid resolution request

Changing that to https://identifiers.org/HP:0000118 works better, and points to https://hpo.jax.org/app/browse/term?id=HP:0012830

But HP has changed their redirect, which is therefore now broken.

The correct link in HPO is: https://hpo.jax.org/app/browse/term/HP:0012830

**Comment by njoannin** [comment]
I was hoping that broken links and technical issues would be resolved quickly.

Unfortunately, I see this is not the case. Therefore, we cannot rely on identifiers.org for this service, and we are better off not using it.

This is really a shame, because this would be a really useful service otherwise.

**Comment by mbdebian** [comment]
Hi @njoannin ,
I'm very sorry you decided to drop the possibility of using our services, at identifiers.org we do our best to support our community and offer the best possible service with the bandwidth we currently have. We understand that, sometimes, some issues, requests or activities may get on the way, but we'd like to state that our registry health is of the utmost importance for us, and we'll address this issue as soon as possible.
As an aside, would you mind telling us how you were interested on using our services? We may be of better help if we understand your prospective usage of our services.
Thanks again for reaching out with feedback on the registry data.
Please, don't hesitate to get in touch again should you have any other questions.
Kind Regards,
Manuel

**Comment by njoannin** [comment]
Hi @mbdebian ,

Thanks for getting back to me on this issue.
Our company provides a text mining solution, which includes the use of publicly available ontologies. We make sure that whenever a term from an ontology is found, that our customers (universities, pharma, biotech, hospitals, healthcare industry) can easily get to the provider's page for it:

 * It allows to direct traffic to the ontology providers website (useful for them to show their resource is used and useful)
 * It allows our customers to be aware of these source providers, and for them to easily link to it, and find additional information that might be useful for them

For this, we have a linkout system, which embeds the concept URL in our results page.

I was hoping to be able to use identifiers.org for this purpose, instead of maintaining our own list of linkouts.

In this particular case, HPO has changed their link over two months ago, but the identifiers.org link has not been updated yet.

If we were using identifiers.org, then for over two months our customers and the data source provider would not have been able to reach each other. That is way too long a turnover time for a broken link, which should be a quick and easy fix.

I do understand that the identifiers.org resource might be understaffed, and cannot address all the issues that come up in a timely fashion. However, for our purpose, we cannot go so long with a broken resource.

If the policy on prioritising the updating of broken links ever changes, please get in touch and I will definitely reconsider using the service, which I think is a great idea!

**Comment by njoannin** [comment]
PS: if you have a Continuous Integration system, it should be rather straight forward to run nightly a test suite that checks that each indentifier in the registry is still valid :)

**Comment by mbdebian** [comment]
I’m glad to let you know that this entry has just been corrected in identifiers.org registry, and it will be picked up by our resolution services along the next few minutes.
Please, keep in mind that the sample URL showing lowercase ‘hp’ instead of uppercase ‘HP’ is a bug on the UI when dealing with ontologies, a special case in identifiers.org registry, that we have already queued in our backlog for fixing, but it doesn’t affect our resolution services.
Thanks again for reaching out to us, and bringing this issue to our attention.
Kind Regards,
Manuel
