### ISSUE TITLE
mod vs. MOD

### ISSUE THREAD

**Issue by edeutsch** [identifiers-org/identifiers-org.github.io#82]
Hi, at this page:

https://registry.identifiers.org/registry/mod

there is a hyperlink to an example URL:

https://identifiers.org/mod:00001

When I click on this link, I get error:

INVALID resolution request for 'mod:00001', due to 'Resolution request 'mod:00001' is NOT ABOUT A NAMESPACE; For namespace 'mod', provided local ID 'mod:00001' DOES NOT MATCH local IDs definition pattern '^MOD:\d{5}''

If I change the URL manually to:

https://identifiers.org/MOD:00001

then it works as expected.

What would be the appropriate way to remedy this?

thanks,
Eric

**Comment by njoannin** [comment]
That is the case with HP too: https://identifiers.org/hp:0000118 vs. https://identifiers.org/HP:0000118

Others work as expected, e.g. MeSH

**Comment by cmungall** [comment]
Also true for MGI

https://registry.identifiers.org/registry/mgi

gives https://identifiers.org/mgi:2442292 as an example, but I get the same error. Fixing to upper case works

Note that this works:

http://n2t.net/mgi:2442292

FWIW, MGI and HP use upper case as canonical and this should be encouraged in identifiers.org documentation, though resolving should be lax

**Comment by cmungall** [comment]
It looks like this is a known issue for multiple ID spaces, e.g. #72 - shouldn't this be a straightforward fix to do a case-insensitive string match?

**Comment by mbdebian** [comment]
Dear @edeutsch , 
Thanks a lot for reporting this issue, it has now been fixed and released to production.
Best Regards,
Manuel
