### ISSUE TITLE
insdc.gca pattern is too restrictive

### ISSUE THREAD

**Issue by jmfernandez** [identifiers-org/identifiers-org.github.io#84]
I have just realized that current pattern for `insdc.gca` identifiers, `^GC[AF]_[0-9]{9}\.[0-9]$` , is too restrictive, because the identifier could end with more than one digit. For instance, GRCh38 RefSeq assembly accession is GCF_000001405.26:

https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26/

So, I guess the pattern should be something like `^GC[AF]_[0-9]{9}\.[0-9]+$` or `^GC[AF]_[0-9]{9}\.[1-9][0-9]*$`

**Comment by mbdebian** [comment]
Hi @jmfernandez ,

Thanks for reaching out on this, I have updated the regex with the following
```
^GC[AF]_[0-9]{9}\.[0-9]+$
```

As the previous one was allowing '.0' to match.

Kind Regards,
Manuel
