### ISSUE TITLE
Sample ID Resolver issue

### ISSUE THREAD

**Issue by ashepherd** [identifiers-org/identifiers-org.github.io#86]
I'm trying to register a persistent identifier service for geophysical samples, and inn completing the form, I am getting a 400 error from `https://registry.api.identifiers.org/prefixRegistrationApi/validateSampleId`
for SampleID: `HRV003M16`
and URL Pattern: `https://doi.org/10273/{$id}`

The error message I receive says, 
`Id 'HRV003M16' does not exist in 'https://doi.org/10273/HRV003M16'`.

despite the resolver working: [https://doi.org/10273/HRV003M16](https://doi.org/10273/HRV003M16)

The JSON response was:
```
{"apiVersion":"1.0","errorMessage":"Id 'HRV003M16' does not exist in 'https://app.geosamples.org/sample/igsn/HRV003M16'","payload":{"comment":"VALIDATION FAILED","token":""}}
```
and request payload: 
```
{"apiVersion":"1.0","payload":{"sampleId":"HRV003M16","providerUrlPattern":"https://doi.org/10273/{$id}"}}
```

The resolving service also works for the following URL patterns if that is helpful:

`https://app.geosamples.org/sample/igsn/{$id}`
`https://hdl.handle.net/10273/{$id}`

![IGSN-Identifiers_org](https://user-images.githubusercontent.com/2117576/75985201-de508100-5eb9-11ea-86da-1c1677cf3274.png)

Could you help register this identifier service?

**Comment by mbdebian** [comment]
Hi @ashepherd ,
Thanks a lot for reporting this, please, let me have a look at it and I'll come back to you with my findings.
Kind Regards,
Manuel

**Comment by mbdebian** [comment]
This is the problem:
When the validator check [https://doi.org/10273/HRV003M16](https://doi.org/10273/HRV003M16)
This is the response it gets:
```
HTTP/2 302 
date: Thu, 05 Mar 2020 13:32:46 GMT
content-type: text/html;charset=utf-8
content-length: 181
set-cookie: __cfduid=d62ed2c0db08e1d149eed3a10d0c828871583415165; expires=Sat, 04-Apr-20 13:32:45 GMT; path=/; domain=.doi.org; HttpOnly; SameSite=Lax; Secure
location: http://data.geosamples.org/sample/igsn/HRV003M16
expires: Fri, 06 Mar 2020 13:32:45 GMT
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=31536000; includeSubDomains; preload
server: cloudflare
cf-ray: 56f43472fb1ef3df-LHR
```
It will follow then the 302 redirection to (http://data.geosamples.org/sample/igsn/HRV003M16)[http://data.geosamples.org/sample/igsn/HRV003M16], obtaining the following response:
```
HTTP/1.1 301 Moved Permanently
Date: Thu, 05 Mar 2020 13:33:00 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/5.4.45
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Content-Type-Options: nosniff
Location: https://app.geosamples.org/sample/igsn/HRV003M16
Content-Length: 256
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://app.geosamples.org/sample/igsn/HRV003M16">here</a>.</p>
</body></html>
```
And this is the problem, that last URL sends back an HTTP 301, which means permanent redirection, and this is rejected by the validation subsystem.

HTTP 302 responses are accepted as a widely used URL beautifying mechanism, but when the response is HTTP 301, it means the resource has moved somewhere else permanently, thus, the given URL is no longer valid, even if it redirects to the final permanent destination of the resource, the 301 is just a stop point for following redirections.

This validation strategy is on the interest of the community, to cut down the times to access a particular dataset, by cutting down on redirections.

So, for registering this, there is a workaround this, to get the prefix registration accepted:
- Please, change the URL pattern to the following: (https://postman-echo.com/get?{$id})[https://postman-echo.com/get?{$id}]
- Leave everything else as it is, this will make the validation system to check (https://postman-echo.com/get?HRV003M16)[https://postman-echo.com/get?HRV003M16], which will come back as HTTP 200.
- Once I have the prefix request in the curation queue, I can override the validation subsystem with your original URL.

Kind Regards,
Manuel

**Comment by ashepherd** [comment]
thank you, @mbdebian ! identifiers.org is such a great resource! much appreciated

**Comment by mbdebian** [comment]
I'm glad identifiers.org is being useful for the community!
I can confirm that we received your prefix registration request and it's now in the review stage.
Kind Regards,
Manuel
