### ISSUE TITLE
"PASS#####" accession IDs in PeptideAtlas not resolving

### ISSUE THREAD

**Issue by AlexandraPhil** [identifiers-org/identifiers-org.github.io#88]
Hi,

A dataset in PeptideAtlas has the following accession ID: PASS01441

However, when I use the identifiers sample URL for PeptideAtlas to create a persistent link to this dataset, this link: https://identifiers.org/peptideatlas:PASS01441 does not resolve.

Is is possible to provide me with a link that resolves and directs me to this dataset?
This should be the landing page of the identifiers link:  http://www.peptideatlas.org/PASS/PASS01441

Thanks!

Best wishes,
Alexandra

**Comment by mbdebian** [comment]
Hi @AlexandraPhil ,
I'd like to thank you for rising this issue.
In identifiers.org, peptide atlas ID [namespace]() is defined by the following regular expression:
```
^PAp[0-9]{8}$
```
This information is used by our resolution services to check whether the given LUI (_Locally Unique ID_) belongs to this ID space, before attempting to resolve the given compact identifier.
In this case, compact identifier _peptideatlas:PASS01441_ does not match the aforementioned regular expression,  thus, the resolution services will return an error.
After checking your link to [PASS01441](http://www.peptideatlas.org/PASS/PASS01441), I can see this namespace may need a regular expression update.
I'd like to introduce @edeutsch into the conversation, as he is listed as a contact for peptide atlas, and @hHermjakob from identifiers.org
Thanks again for this feedback @AlexandraPhil 
@edeutsch, could you provide updated information about peptide atlas for its registered namespace?
Best Regards,
Manuel

**Comment by AlexandraPhil** [comment]
Thanks for looking into this further!

Alexandra

**Comment by edeutsch** [comment]
Hi everyone, PeptideAtlas has several different types of identifiers.
^PAp[0-9]{8}$ remains valid for PeptideAtlas peptide identifiers.
$PASS[0-9]{5}$ is valid for PeptideAtlas submitted datasets, a new entry.
So, the result is the PASS##### identifiers should be added, but not replace the existing record.
The proposed landing page above is correct.

Please let me know if you need more information

**Comment by AlexandraPhil** [comment]
Hi @edeutsch, 

Thanks for the fast response. The link https://identifiers.org/peptideatlas:PASS01441 still does not resolve, and it's not very clear from your message what the next step will be.

Will I be notified when we have an identifiers link that works (with the accession PASS01441)?

Thanks!!

Alexandra

**Comment by mbdebian** [comment]
> Hi everyone, PeptideAtlas has several different types of identifiers.
> ^PAp[0-9]{8}$ remains valid for PeptideAtlas peptide identifiers.
> $PASS[0-9]{5}$ is valid for PeptideAtlas submitted datasets, a new entry.
> So, the result is the PASS##### identifiers should be added, but not replace the existing record.
> The proposed landing page above is correct.
> 
> Please let me know if you need more information

Thanks a lot for your prompt reply @edeutsch 
As we don't support multiple regular expressions for a given namespace, would you be willing to provide a regular expression for the existing namespace and URL pattern for the resource that covers both IDs if possible?
Another option, would be registering a new namespace that could cover PASS##### identifiers.
Thanks again for your help @edeutsch 
Kind Regards,
Manuel

**Comment by edeutsch** [comment]
Hi Manuel, I'm not sure I really understand your questions. I'm guessing maybe we want to register a new namespace? PAp12345678 identifiers and PASS12345 identifiers are for two completely separate concepts, so I guess they get two separate namespaces? I'm not certain I understand what a "namespace" is.

PAp12345678 is correct as it was.
We just need to add PASS12345. Are you able to do that?

thanks,
Eric

**Comment by edeutsch** [comment]
@AlexandraPhil I think this is something that Manuel and I need too resolve first, and then it will work for you. So I think you just need to wait for a bit more..

**Comment by AlexandraPhil** [comment]
Hi @edeutsch and @mbdebian

Thanks for looking further into this. Do you know approximately how long this will take?

Thanks

Alexandra

**Comment by edeutsch** [comment]
Hi @AlexandraPhil I don't have a time estimate. I think we are waiting for @mbdebian to create a namespace for PASS12345. I don't know how to do it.

**Comment by AlexandraPhil** [comment]
Thanks @edeutsch! That's fine. Just let me know once it's done.

Thanks again!

Alexandra

**Comment by mbdebian** [comment]
> Hi Manuel, I'm not sure I really understand your questions. I'm guessing maybe we want to register a new namespace? PAp12345678 identifiers and PASS12345 identifiers are for two completely separate concepts, so I guess they get two separate namespaces? I'm not certain I understand what a "namespace" is.
> 
> PAp12345678 is correct as it was.
> We just need to add PASS12345. Are you able to do that?
> 
> thanks,
> Eric

Hi @edeutsch ,
Sorry for the delay getting back to you, I think you're right, being a separated thing, they need their own namespace.
Could you submit the details via our prefix registration request [form](https://registry.identifiers.org/prefixregistrationrequest) I'll then get it in the registry, and live on our resolution services.
Thanks a lot for your help on this @edeutsch 
Best Regards,
Manuel

**Comment by mbdebian** [comment]
I'm looking forward to processing the new prefix registration request.
Thanks @edeutsch and @AlexandraPhil 
Best Regards,
Manuel

**Comment by edeutsch** [comment]
Hi everyone, I went to the request form sent by Manuel above, and started to fill in the form. While pondering how to make the fields I filled in compatible with our existing record, I went to:
https://registry.identifiers.org/registry
and typed in "pep" and find that record, an I see that we already have two records. The one for PASS is the second one:
![image](https://user-images.githubusercontent.com/12707718/77195123-5c0db280-6a9e-11ea-9323-e78b5aacc510.png)
I don't find a date on the record, but I suppose it's been there for a long time? Or did you just create it, Manuel?

I have not filled in the form because it appears that what we want is already there.
Manuel, can you clarify?

thanks,
Eric

**Comment by edeutsch** [comment]
So rewinding all the way back to the original post, instead of this:
https://identifiers.org/peptideatlas:PASS01441
it should be:
https://identifiers.org/peptideatlas.dataset:PASS01441

Does that resolve things?

**Comment by AlexandraPhil** [comment]
Excellent! Thank you both very much!

**Comment by AlexandraPhil** [comment]
Excellent! Thanks! It does resolve!

Alexandra

**Comment by AlexandraPhil** [comment]
Thank you both! It does resolve! Thanks a lot!

Alexandra

**Comment by mbdebian** [comment]
> Hi everyone, I went to the request form sent by Manuel above, and started to fill in the form. While pondering how to make the fields I filled in compatible with our existing record, I went to:
> https://registry.identifiers.org/registry
> and typed in "pep" and find that record, an I see that we already have two records. The one for PASS is the second one:
> ![image](https://user-images.githubusercontent.com/12707718/77195123-5c0db280-6a9e-11ea-9323-e78b5aacc510.png)
> I don't find a date on the record, but I suppose it's been there for a long time? Or did you just create it, Manuel?
> 
> I have not filled in the form because it appears that what we want is already there.
> Manuel, can you clarify?
> 
> thanks,
> Eric

Hi @edeutsch , 

Thanks a lot for looking into this, the record was already there.

Please, don't hesitate to let me know if you'd like me to update any details in peptideatlas.dataset

Thanks,
Manuel
