### ISSUE TITLE
EGA study id not resolving

### ISSUE THREAD

**Issue by TrisSN** [identifiers-org/identifiers-org.github.io#91]
I have this accession id: EGAS00001003745
I can see the page via this link: https://ega-archive.org/studies/EGAS00001003745
Identifiers gives this, but it doesn't resolve: https://identifiers.org/ega.study:EGAS00001003745

It would be great if you can either resolve or let me know you can't resolve this within the next week, as we have a paper centred around this dataset waiting to be published.

**Comment by mbdebian** [comment]
Hi @TrisSN,
I just wanted to let you know that we are looking into this.
Thanks for reporting the issue,
Manuel

**Comment by mbdebian** [comment]
I have checked with identifiers.org registry, and our resolution services resolve to the following [EGA](https://www.ebi.ac.uk/ega/studies/EGAS00001003745) correctly, so I've checked with [EGA Resource](https://www.ebi.ac.uk/ega) and, apparently, some of their services are undergoing maintenance between 2nd March and 3rt April (see screen capture).
This may be affecting access to EGA Studies.
Could you please rise a support request with them?
Thanks a lot for raising this issue @TrisSN , please, don't hesitate to let me know if you need anything else.
Kind Regards,
Manuel
![Captura de pantalla 2020-03-30 a las 14 15 07](https://user-images.githubusercontent.com/8855107/77916365-def9ee80-7290-11ea-96e3-1fc02e722874.png)
