### ISSUE TITLE
Are namespace regex patterns supposed to match sampleId?

### ISSUE THREAD

**Issue by dhimmel** [identifiers-org/identifiers-org.github.io#99]
While working on https://github.com/manubot/manubot/pull/219, I noticed several namespaces from https://registry.api.identifiers.org/restApi/namespaces have regex `pattern`s that do not match the `sampleId`.

Here's the complete list I found using Python's `re.fullmatch`:

```
ark regex ^(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$ does not match /12345/fk1234
bto regex ^BTO:\d{7}$ does not match 0000146
cco regex ^CCO\:\w+$ does not match 0000003
chebi regex ^CHEBI:\d+$ does not match 36927
cl regex ^CL:\d{7}$ does not match 0000232
did regex ^did:[a-z0-9]+:[A-Za-z0-9.\-:]+$ does not match sov:WRfXPg8dantKVubE3HX8pw
doid regex ^DOID\:\d+$ does not match 11337
eco regex ECO:\d{7}$ does not match 0000006
envo regex ^ENVO:\d{8}$ does not match 09200010
eo regex ^(P)?EO\:\d{7}$ does not match 0007404
fma regex ^FMA:\d+$ does not match 67112
foodon regex ^FOODON:[0-9]{8}$ does not match 03307879
go regex ^GO:\d{7}$ does not match 0006915
gramene.growthstage regex ^GRO\:\d+$ does not match 0007133
gwascentral.phenotype regex ^HGVP\d+$ does not match HGVPM623
hp regex ^HP:\d{7}$ does not match 0000118
ma regex ^MA:\d+$ does not match 0002502
mge regex ^mge:\d+$ does not match 2
mgi regex ^MGI:\d+$ does not match 2442292
mir regex ^MIR:\d{8}$ does not match 00100037
mod regex ^MOD:\d{5} does not match 00001
mp regex ^MP:\d{7}$ does not match 0005452
ms regex ^MS:\d{7}$ does not match 1000001
mzspec regex ^mzspec:.+$ does not match PXD002255::ES_XP_Ubi_97H_HCD_349:scan:9617:LAEIYVNSSFYK/2
nmr regex ^NMR:\d+$ does not match 1000003
ocid regex ocid:[0-9]{12} does not match 190000021540
panther.pthcmp regex ^G|P|U|C|S\d{5}$ does not match P00266
pato regex ^PATO:\d{7}$ does not match 0001998
po regex ^PO:\d+$ does not match 0009089
pr regex ^PR:P?\d+$ does not match 000000024
psimi regex ^MI:\d{4}$ does not match 0308
pw regex ^PW:\d{7}$ does not match 0000208
rrid regex ^RRID:[a-zA-Z]+.+$ does not match AB_262044
sbo regex ^SBO:\d{7}$ does not match 0000262
so regex ^SO:\d{7}$ does not match 0000704
swh regex ^swh:[1-9]:[a-z][a-z][a-z]:[a-f0-9]+$ does not match 1:rev:309cf2674ee7a0749978cf8265ab91a60aea0f7d
swisslipid regex ^SLM:\d+$ does not match 000048885
uberon regex ^UBERON\:\d+$ does not match 0008203
uo regex ^UO:\d{7}? does not match 0000080
vario regex ^VariO:\d+$ does not match 0294
```

Many of the issues appear to arise from the `pattern` expecting the prefix, while the `sampleId` omitting the prefix. How is the regex `pattern` intended to be used? Do I need to do additional steps before applying the regex to sample identifiers?

**Comment by cthoyt** [comment]
Check my comment at https://github.com/manubot/manubot/pull/219/files#r409195015, I think that will solve lots of these issues

**Comment by cthoyt** [comment]
Inside the OBO documents, the identifiers are considered as local identifirs. So in the GO.obo file, all of the `id:` fields would get the GO prefix. But the local identifiers are also prefixed, which causes the GO:GO: problem. That's why identifiers.org keeps track of which ones have the namespace in the local unique identifier, so it knows to strip the first one away

The real upsetting example is the NCBITaxon namespace, where the identifiers.org prefix is `taxonomy` but the local unique identifiers are prefixed with `NCBITaxon`... I've done a lot of work with parsing OBO stuff lately at https://github.com/pyobo/pyobo and done LOTS of curation of all the weird variants people have used for prefixes when they meant something else throughout the OBO Foundry. would be happy to chat on an issue there if you wanted to know more

**Comment by mbdebian** [comment]
They're all cases where the namespace prefix is embedded in the LUI, It is an internal processing we do in identifiers.org for dealing with those special cases.
Please, keep in mind that the Sample URL shown on the frontend matches the regular expression, and it's the valid URL.
Also, please, have a look at this [issue](https://github.com/identifiers-org/identifiers-org.github.io/issues/65) where I include an explanation on why some namespaces have a particular flag activated, and therefore using LUIs in the resolution services instead of full Compact Identifiers.
Thanks!
Manuel

**Comment by dhimmel** [comment]
> The real upsetting example is the NCBITaxon namespace, where the identifiers.org prefix is taxonomy but the local unique identifiers are prefixed with NCBITaxon

Is this similar to the `gramene.growthstage` prefix` where [namespaceEmbeddedInLui is true](https://registry.api.identifiers.org/restApi/namespaces/search/findByPrefix?prefix=gramene.growthstage), but where compact IDs must [start with](https://registry.identifiers.org/registry/gramene.growthstage) `GRO`?

> They're all cases where the namespace prefix is embedded in the LUI, It is an internal processing we do in identifiers.org for dealing with those special cases.

Similar to my reply at https://github.com/identifiers-org/identifiers-org.github.io/issues/100#issuecomment-614679142, is there anyway to expose this "internal processing" as part of the API?

My goal is to determine whether a given string is a valid compact identifier, and if so convert it to an `identifiers.org` URL. It seems like a bad thing if I have to re-implement any complicated logic to perform this task.

**Comment by dhimmel** [comment]
In https://github.com/manubot/manubot/pull/219/commits/779ef95562deb602d4d820edb7b97990f77dd384, I updated our code for the namespaceEmbeddedInLui quirks.

There are now only a few remaining corner cases our tests detect:

```
manubot/cite/tests/test_curie.py::test_get_namespaces_with_compile_patterns eo identifiers use curiePrefix PEO
gramene.growthstage identifiers use curiePrefix GRO
gwascentral.phenotype regex ^HGVP\d+$ does not match HGVPM623
panther.pthcmp regex ^G|P|U|C|S\d{5}$ does not match P00266
psimi identifiers use curiePrefix MI
```

For https://registry.identifiers.org/registry/gwascentral.phenotype, it seems the `^HGVP\d+$` regex is missing a `P` that is in the sample LUI of `HGVPM623`.

For https://registry.identifiers.org/registry/panther.pthcmp, I think the regex should be updated to `^(G|P|U|C|S)\d{5}$`.

For the `eo`, `gramene.growthstage`, and `psimi` namespace prefixes, the actual prefixes used by CURIEs do not match (ignoring case). I'm not sure whether this is intentional or not.

**Comment by dhimmel** [comment]
Reran the manubot test `test_get_namespaces_with_compile_patterns` which reported the follows issues with the identifiers.org data as of 2021-10-29 / https://github.com/manubot/manubot/commit/11f7192e32aa280145e118135f0041a41a1b02d1


```
gramene.growthstage identifiers use curiePrefix GRO
oma.hog regex ^HOG:[0-9]{7}(\.[0-9a-z.]+)?(_[0-9]+)?$ does not match HOG:HOG:0459895
oma.hog identifiers use curiePrefix HOG
panther.pthcmp regex ^G|P|U|C|S\d{5}$ does not match P00266
```

So looks like only one of the issues [reported](https://github.com/identifiers-org/identifiers-org.github.io/issues/99#issuecomment-627006826) in May 2020 has been fixed.

We're switching to using Bioregistry for our primary registry resource as per https://github.com/manubot/manubot/issues/305. So won't be able to continue providing these reports. Although I encourage Identifiers.org to validate their regexes against sample identifiers and address the cases where the prefix conflicts with embedded namespace.
